// ── Static curriculum data ────────────────────────────────────────
// Ported from legacy/js/data.js

export type SubjectDef = { id: string; name: string; icon: string };
export type BadgeDef = { id: string; icon: string; name: string; desc: string };

// ── 114 Surahs: [name, ayahCount] ────────────────────────────────
export const SURAHS: [string, number][] = [
  ["Al-Fatihah", 7],
  ["Al-Baqarah", 286],
  ["Aal Imran", 200],
  ["An-Nisa", 176],
  ["Al-Ma'idah", 120],
  ["Al-An'am", 165],
  ["Al-A'raf", 206],
  ["Al-Anfal", 75],
  ["At-Tawbah", 129],
  ["Yunus", 109],
  ["Hud", 123],
  ["Yusuf", 111],
  ["Ar-Ra'd", 43],
  ["Ibrahim", 52],
  ["Al-Hijr", 99],
  ["An-Nahl", 128],
  ["Al-Isra", 111],
  ["Al-Kahf", 110],
  ["Maryam", 98],
  ["Ta-Ha", 135],
  ["Al-Anbiya", 112],
  ["Al-Hajj", 78],
  ["Al-Mu'minun", 118],
  ["An-Nur", 64],
  ["Al-Furqan", 77],
  ["Ash-Shu'ara", 227],
  ["An-Naml", 93],
  ["Al-Qasas", 88],
  ["Al-Ankabut", 69],
  ["Ar-Rum", 60],
  ["Luqman", 34],
  ["As-Sajdah", 30],
  ["Al-Ahzab", 73],
  ["Saba", 54],
  ["Fatir", 45],
  ["Ya-Sin", 83],
  ["As-Saffat", 182],
  ["Sad", 88],
  ["Az-Zumar", 75],
  ["Ghafir", 85],
  ["Fussilat", 54],
  ["Ash-Shura", 53],
  ["Az-Zukhruf", 89],
  ["Ad-Dukhan", 59],
  ["Al-Jathiyah", 37],
  ["Al-Ahqaf", 35],
  ["Muhammad", 38],
  ["Al-Fath", 29],
  ["Al-Hujurat", 18],
  ["Qaf", 45],
  ["Adh-Dhariyat", 60],
  ["At-Tur", 49],
  ["An-Najm", 62],
  ["Al-Qamar", 55],
  ["Ar-Rahman", 78],
  ["Al-Waqi'ah", 96],
  ["Al-Hadid", 29],
  ["Al-Mujadila", 22],
  ["Al-Hashr", 24],
  ["Al-Mumtahanah", 13],
  ["As-Saff", 14],
  ["Al-Jumu'ah", 11],
  ["Al-Munafiqun", 11],
  ["At-Taghabun", 18],
  ["At-Talaq", 12],
  ["At-Tahrim", 12],
  ["Al-Mulk", 30],
  ["Al-Qalam", 52],
  ["Al-Haqqah", 52],
  ["Al-Ma'arij", 44],
  ["Nuh", 28],
  ["Al-Jinn", 28],
  ["Al-Muzzammil", 20],
  ["Al-Muddaththir", 56],
  ["Al-Qiyamah", 40],
  ["Al-Insan", 31],
  ["Al-Mursalat", 50],
  ["An-Naba", 40],
  ["An-Nazi'at", 46],
  ["Abasa", 42],
  ["At-Takwir", 29],
  ["Al-Infitar", 19],
  ["Al-Mutaffifin", 36],
  ["Al-Inshiqaq", 25],
  ["Al-Buruj", 22],
  ["At-Tariq", 17],
  ["Al-A'la", 19],
  ["Al-Ghashiyah", 26],
  ["Al-Fajr", 30],
  ["Al-Balad", 20],
  ["Ash-Shams", 15],
  ["Al-Layl", 21],
  ["Ad-Duha", 11],
  ["Ash-Sharh", 8],
  ["At-Tin", 8],
  ["Al-Alaq", 19],
  ["Al-Qadr", 5],
  ["Al-Bayyinah", 8],
  ["Az-Zalzalah", 8],
  ["Al-Adiyat", 11],
  ["Al-Qari'ah", 11],
  ["At-Takathur", 8],
  ["Al-Asr", 3],
  ["Al-Humazah", 9],
  ["Al-Fil", 5],
  ["Quraysh", 4],
  ["Al-Ma'un", 7],
  ["Al-Kawthar", 3],
  ["Al-Kafirun", 6],
  ["An-Nasr", 3],
  ["Al-Masad", 5],
  ["Al-Ikhlas", 4],
  ["Al-Falaq", 5],
  ["An-Nas", 6],
];

// ── Subjects (9 subjects matching legacy exactly) ────────────────
export const SUBJECTS: SubjectDef[] = [
  { id: "quran", name: "Quran", icon: "📖" },
  { id: "tajweed", name: "Tajweed", icon: "🎙️" },
  { id: "tafsir", name: "Tafsir", icon: "📘" },
  { id: "arabic", name: "Arabic", icon: "✍️" },
  { id: "aqeedah", name: "Aqeedah", icon: "🕌" },
  { id: "fiqh", name: "Fiqh", icon: "📜" },
  { id: "seerah", name: "Seerah", icon: "📚" },
  { id: "akhlaq", name: "Akhlaq", icon: "🤲" },
  { id: "math", name: "Math", icon: "🔢" },
  { id: "science", name: "Science", icon: "🔬" },
  { id: "english", name: "English", icon: "📝" },
  { id: "adhkar", name: "Adhkar & Dua", icon: "📿" },
  { id: "muttoon", name: "Muttoon", icon: "📕" },
  { id: "coding", name: "Coding", icon: "💻" },
  { id: "computer", name: "Computer", icon: "🖥️" },
  { id: "home-science", name: "Home Science", icon: "🏠" },
  { id: "safety", name: "Safety", icon: "🛡️" },
];

// ── Skills per subject (IXL-style mastery tracking) ──────────────
export const SKILLS: Record<string, string[]> = {
  math: [
    "Counting to 100",
    "Addition within 20",
    "Subtraction within 20",
    "Place value",
    "Multiplication tables",
    "Division basics",
    "Fractions intro",
    "Telling time",
    "Money & coins",
    "Word problems",
  ],
  science: [
    "Living vs non-living",
    "Plant life cycle",
    "Animal habitats",
    "Weather & seasons",
    "The five senses",
    "States of matter",
    "The solar system",
    "Simple machines",
    "Human body basics",
    "Food chains",
  ],
  english: [
    "Letter sounds (phonics)",
    "Sight words",
    "Reading fluency",
    "Reading comprehension",
    "Handwriting",
    "Spelling patterns",
    "Sentence building",
    "Grammar basics",
    "Story writing",
    "Vocabulary",
  ],
  arabic: [
    "Alphabet recognition",
    "Letter forms (begin/mid/end)",
    "Harakat (vowels)",
    "Joining letters",
    "Basic vocabulary",
    "Simple sentences",
    "Listening comprehension",
    "Conversation basics",
  ],
  tajweed: [
    "Makharij (articulation points)",
    "Noon sakinah rules",
    "Meem sakinah rules",
    "Madd (elongation)",
    "Qalqalah",
    "Stopping & starting",
  ],
  tafsir: [
    "Juz Amma meanings",
    "Short surahs tafsir",
    "Quran stories",
    "Key themes",
    "Historical context",
  ],
  aqeedah: [
    "Allah is One",
    "Pillars of Iman",
    "Five Pillars of Islam",
    "Names of Allah",
    "Prophets of Allah",
    "Tawhid basics",
  ],
  fiqh: [
    "Wudu steps",
    "Salah basics",
    "Halal food",
    "Fasting rules",
    "Zakat basics",
    "Hajj overview",
  ],
  seerah: [
    "Prophet's birth",
    "Early life",
    "First revelation",
    "Migration to Madinah",
    "Key battles",
    "His character",
  ],
  akhlaq: [
    "Emotional intelligence",
    "Empathy",
    "Conflict resolution",
    "Honesty",
    "Kindness",
    "Patience (Sabr)",
    "Gratitude (Shukr)",
    "Respecting elders",
    "Controlling anger",
  ],
  adhkar: [
    "Morning adhkar",
    "Evening adhkar",
    "Ayatul Kursi",
    "Daily duas",
    "Istighfar",
  ],
  muttoon: [
    "Nawaaqid Al-Islam",
    "Al-Qawaid Al-Arba",
    "Al-Usool Al-Thalaatha",
    "Al-Arbaeen Nawawi",
    "Ajrumiyya",
  ],
  coding: [
    "Scratch projects",
    "Python basics",
    "HTML/CSS",
    "Algorithms",
    "Debugging",
  ],
  computer: [
    "Keyboard skills",
    "File management",
    "Internet safety",
    "Word processing",
    "Spreadsheets",
  ],
  safety: [
    "Body safety",
    "Road safety",
    "Fire safety",
    "Water safety",
    "Emergency response",
  ],
  "home-science": [
    "Nutrition basics",
    "Cooking skills",
    "First aid",
    "Household management",
    "Gardening",
  ],
  quran: [
    "Al-Fatiha memorization",
    "Short surahs (113-114)",
    "Juz Amma recitation",
    "Tilawah fluency",
    "Hifz retention",
  ],
};

// ── Mastery levels ───────────────────────────────────────────────
export const LEVELS: string[] = [
  "Not started",
  "Practicing",
  "Proficient",
  "Mastered",
];

// ── Recommended Islamic children's books ─────────────────────────
export const REC_BOOKS: [string, string][] = [
  ["The Story of the Elephant", "Hajera Memon"],
  ["Ilyas and Duck Search for Allah", "Omar Khawaja"],
  ["Migo and Ali: Love for the Prophets", "Zanib Mian"],
  ["The Best Eid Ever", "Asma Mobin-Uddin"],
  ["My First Quran Storybook", "Saniyasnain Khan"],
  ["Allah Made Everything", "Zain Bhikha"],
  ["Golden Domes and Silver Lanterns", "Hena Khan"],
  ["I Say Alhamdulillah", "Noor H. Dee"],
  ["The Gift of Ramadan", "Rabiah York Lumbard"],
  ["365 Days with the Prophet Muhammad", "Nurdan Damla"],
];

// ── Standard day template [subjectId, title, slot] ───────────────
export const STD_DAY: [string, string, string][] = [
  ["quran", "Memorize new ayahs", "After Fajr"],
  ["tajweed", "Tajweed practice", "After Fajr"],
  ["aqeedah", "Aqeedah lesson", "Morning"],
  ["math", "Math practice", "Morning"],
  ["english", "Reading & phonics", "Morning"],
  ["arabic", "Arabic letters & words", "After Dhuhr"],
  ["tafsir", "Tafsir story time", "After Dhuhr"],
  ["seerah", "Seerah story time", "After Dhuhr"],
  ["fiqh", "Fiqh lesson", "After Asr"],
  ["akhlaq", "Character building", "After Asr"],
  ["science", "Science exploration", "After Asr"],
];

// ── Badge definitions ────────────────────────────────────────────
export const BADGE_DEFS: BadgeDef[] = [
  { id: "first", icon: "🌟", name: "First Step", desc: "Complete your first task" },
  { id: "perfect", icon: "💯", name: "Perfect Day", desc: "Finish every task in one day" },
  { id: "streak3", icon: "🔥", name: "3-Day Streak", desc: "3 perfect days in a row" },
  { id: "streak7", icon: "⚡", name: "7-Day Streak", desc: "7 perfect days in a row" },
  { id: "surah3", icon: "📖", name: "Surah Star", desc: "Memorize 3 surahs" },
  { id: "surah10", icon: "🕌", name: "Juz Amma Journey", desc: "Memorize 10 surahs" },
  { id: "book3", icon: "📚", name: "Bookworm", desc: "Finish 3 books" },
  { id: "master5", icon: "🏆", name: "Skill Master", desc: "Master 5 skills" },
];

// ── Helper: look up a subject by id ──────────────────────────────
export function subj(id: string): SubjectDef {
  return SUBJECTS.find((s) => s.id === id) || { id, name: id, icon: "📌" };
}
