import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

export async function seedMuttoon() {
  const existing = await prisma.$queryRawUnsafe<{cnt: number}[]>(
    "SELECT COUNT(*) as cnt FROM \"CurriculumTopic\" WHERE subject='muttoon'"
  );
  if (Number(existing[0]?.cnt ?? 0) > 0) {
    console.log('  Muttoon topics already exist — skipping.');
    return;
  }
  console.log('Seeding Muttoon Talibul Ilm curriculum...');

  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
('mt-001','muttoon','muttoon-level1',3,'3-4','Introduction to Muttoon Talibul Ilm','Overview of the 5-level Muttoon system designed by Sheikh Abdul Muhsin Al-Qaasim (Imam of Masjid Al-Nabawi). A structured path for the student of knowledge.','introduction',2,'["verbal"]','[""]','Muttoon book, teacher guidance'),
('mt-002','muttoon','muttoon-nawaaqid',3,'3-4','Nawaaqid Al-Islam — Introduction','Learn the 10 nullifiers of Islam by Muhammad ibn Abd al-Wahhab. Understanding what nullifies one''s Islam is essential for every Muslim.','introduction',3,'["verbal"]','["mt-001"]','Nawaaqid booklet, teacher'),
('mt-003','muttoon','muttoon-nawaaqid',3,'3-4','Nawaaqid #1-3: Shirk, Kufrr, Setting up intercessors','Nullifier 1: Associating partners with Allah (Shirk). Nullifier 2: Disbelief in Allah''s names/attributes. Nullifier 3: Setting up intercessors between oneself and Allah.','practice',3,'["verbal"]','["mt-002"]','Nawaaqid booklet'),
('mt-004','muttoon','muttoon-nawaaqid',3,'3-4','Nawaaqid #4-6: Rejecting predestination, Prophethood, Shariah','Nullifier 4: Believing someone other than Prophet Muhammad ﷺ has knowledge of unseen. Nullifier 5: Rejecting any part of Shariah. Nullifier 6: Hating what Prophet ﷺ brought.','practice',3,'["verbal"]','["mt-003"]','Nawaaqid booklet'),
('mt-005','muttoon','muttoon-nawaaqid',3,'3-4','Nawaaqid #7-10: Sorcery, Supporting disbelievers, Mocking Islam, Abandoning Islam','Nullifier 7: Sorcery. Nullifier 8: Supporting disbelievers against Muslims. Nullifier 9: Mocking Islam. Nullifier 10: Abandoning the Muslim community.','practice',3,'["verbal"]','["mt-004"]','Nawaaqid booklet'),
('mt-006','muttoon','muttoon-qawaid',3,'3-4','Al-Qawaa''id Al-Arba'' — The Four Principles','Learn the 4 principles by which every Muslim should investigate matters of belief: (1) Allah exists and is proved by creation, (2) Allah alone is to be worshipped, (3) Prophet Muhammad ﷺ is His Messenger, (4) Religion comes from Allah alone.','practice',4,'["verbal"]','["mt-002"]','Qawaid booklet'),
('mt-007','muttoon','muttoon-usool',3,'3-4','Al-Usool Al-Thalaatha — The Three Fundamental Principles','Learn the 3 questions in the grave: (1) Who is your Lord? (2) What is your religion? (3) Who is this man (Prophet ﷺ)? By Muhammad ibn Abd al-Wahhab.','practice',4,'["verbal"]','["mt-006"]','Usool booklet'),
('mt-008','muttoon','muttoon-arbaeen',3,'3-4','Al-Arba''in An-Nawawi — Introduction','Introduction to the 40 Hadith of Imam Nawawi. "Whoever memorizes 40 hadith in the matter of his religion, Allah will admit him to Paradise." (Ahmad)','introduction',2,'["verbal"]','["mt-001"]','Hadith book, teacher'),
('mt-009','muttoon','muttoon-arbaeen',3,'3-4','Arba''in Hadith #1-5: Actions, Intentions, Religion, Islam basics','Hadith 1: "Actions are by intentions." Hadith 2: "Islam, Iman, Ihsan." Hadith 3: Pillars of Islam. Hadith 4: Pillars of Iman. Hadith 5: "Islam is built on five pillars."','practice',4,'["verbal"]','["mt-008"]','Hadith cards'),
('mt-010','muttoon','muttoon-arbaeen',3,'3-4','Arba''in Hadith #6-10: Hajj, Ihsan, Faith, Intercession','Hadith 6: Hajj. Hadith 7: "Ihsan is to worship Allah as if you see Him." Hadith 8: "No one will enter Paradise by deeds alone." Hadith 9: Intercession. Hadith 10: Prohibition of innovation.','practice',4,'["verbal"]','["mt-009"]','Hadith cards'),
('mt-011','muttoon','muttoon-arbaeen',3,'3-4','Arba''in Hadith #11-20: Core Islamic concepts','Covers hadith about: avoiding doubtful matters, fasting, zakat, jihad, leadership, trust in Allah, seeking knowledge, sincerity, and more.','practice',5,'["verbal"]','["mt-010"]','Hadith cards'),
('mt-012','muttoon','muttoon-arbaeen',3,'3-4','Arba''in Hadith #21-40: Advanced topics','Covers hadith about: innovation, knowledge, heart diseases, wealth, honesty, brotherhood, death, and the hereafter.','practice',5,'["verbal"]','["mt-011"]','Hadith cards'),
('mt-013','muttoon','muttoon-level2',4,'4-5','Tuhfatul Atfaal — Gift for Children','Learn the dua and adhkar from Tuhfatul Atfaal by Imam Al-Jazari. A systematic collection of duas for every occasion in a child''s life.','introduction',3,'["verbal"]','["mt-001"]','Tuhfatul Atfaal book'),
('mt-014','muttoon','muttoon-level2',4,'4-5','Shuruth Al-Salah — Conditions of Prayer','Learn the conditions (shuruth) that must be met before salah is valid: Islam, cleanliness, covering awrah, facing qiblah, time, intention.','practice',4,'["verbal"]','["mt-007"]','Fiqh book, teacher'),
('mt-015','muttoon','muttoon-level2',4,'4-5','Kitab Al-Tawheed — Book of Monotheism','Study the book of Tawheed by Muhammad ibn Abd al-Wahhab. Understanding the three types of Tawheed: Rububiyyah, Uluhiyyah, Asma wa Sifat.','practice',5,'["verbal"]','["mt-006"]','Tawheed book, teacher'),
('mt-016','muttoon','muttoon-level2',4,'4-5','Tawheed categories — Rububiyyah, Uluhiyyah, Asma wa Sifat','Rububiyyah: Allah is the sole Creator, Provider, Controller. Uluhiyyah: worship Allah alone. Asma wa Sifat: Allah''s names and attributes are unique.','practice',4,'["verbal"]','["mt-015"]','Tawheed chart'),
('mt-017','muttoon','muttoon-level2',4,'4-5','Dangers of Shirk — types and prevention','Learn the three types of Shirk: Akbar (major), Asghar (minor), Khafi (hidden). The Prophet ﷺ warned against even small shirk like showing off.','practice',4,'["verbal"]','["mt-015"]','examples, discussion'),
('mt-018','muttoon','muttoon-level3',5,'5-6','Mandhumah Al-Bayquniya — Poem on Quran chapters','Learn the Bayquni poem that lists all 114 surahs of the Quran with brief descriptions. Helps memorize the order and topics of Quran chapters.','practice',5,'["verbal"]','["mt-001"]','Bayquni poem, teacher'),
('mt-019','muttoon','muttoon-level3',5,'5-6','Mandhumah Al-Ilbiri — Hadith terminology poem','Learn the basics of hadith sciences through the Ilbiri poem. Introduction to hadith classification: Sahih, Hasan, Da''if, Mawdu''.','practice',4,'["verbal"]','["mt-018"]','Ilbiri poem, teacher'),
('mt-020','muttoon','muttoon-level3',5,'5-6','Al-Muqadimmah Al-Ajrumiyya — Arabic grammar intro','Study the Ajrumiyya by Ibn Ajurrum. Learn the three types of Arabic words: Ism (noun), Fi''l (verb), Harf (preposition).','practice',5,'["verbal"]','["mt-001"]','Ajrumiyya text, teacher'),
('mt-021','muttoon','muttoon-level3',5,'5-6','Al-Aqeedah Al-Wasitiyya — Creed of Wasit','Study the creed of Wasit by Ibn Taymiyyah. Covers the correct belief of Ahl al-Sunnah wal-Jama''ah regarding Allah''s names and attributes.','practice',4,'["verbal"]','["mt-016"]','Wasitiyya text, teacher'),
('mt-022','muttoon','muttoon-level3',5,'5-6','Ajrumiyya basics — nouns, verbs, prepositions','Deep dive into Arabic grammar: types of nouns (marfu, mansub, majrur), verb forms, preposition rules. Foundation for reading classical texts.','practice',4,'["verbal"]','["mt-020"]','grammar workbook'),
('mt-023','muttoon','muttoon-level3',5,'5-6','Hadith sciences — chains, classification, terminology','Learn: Isnad (chain of narration), Matn (text), Mursal, Mu''allaq, Munqati'' types. How scholars authenticate hadith.','practice',3,'["verbal"]','["mt-019"]','hadith reference books'),
('mt-024','muttoon','muttoon-level4',6,'6-7','Al-Waraqat — Principles of Fiqh (Usul al-Fiqh)','Study Al-Waraqat by Imam al-Juwayni. Learn the sources of Islamic law: Quran, Sunnah, Ijma'', Qiyas. Understand legal rulings (ahkam).','practice',5,'["verbal"]','["mt-020"]','Waraqat text, teacher'),
('mt-025','muttoon','muttoon-level4',6,'6-7','Onwan Al-Hikam — Title of Wisdom','Study the poem on wisdom and effective speech. Learn the principles of eloquent and wise speech in Islam.','practice',3,'["verbal"]','["mt-020"]','poem text, teacher'),
('mt-026','muttoon','muttoon-level4',6,'6-7','Al-Rahabiyyah — Arabic grammar (advanced)','Study the Rahabiyya poem on Arabic grammar. Covers advanced grammatical rules: sentence structures, verb forms, special constructions.','practice',4,'["verbal"]','["mt-022"]','grammar text, teacher'),
('mt-027','muttoon','muttoon-level4',6,'6-7','Al-Aqeedah Al-Tahawiyya — Creed of Imam Tahawi','Study the famous creed of Imam al-Tahawi. The most comprehensive statement of Sunni belief covering: Allah''s oneness, prophethood, the Quran, the Last Day, and predestination.','practice',5,'["verbal"]','["mt-021"]','Tahawiyya text, teacher'),
('mt-028','muttoon','muttoon-level4',6,'6-7','Usul al-Fiqh applications — legal reasoning','Apply the principles of Usul al-Fiqh: how scholars derive rulings from Quran and Sunnah, understanding abrogation, general vs specific, and conditional texts.','practice',4,'["verbal"]','["mt-024"]','fiqh reference, case studies'),
('mt-029','muttoon','muttoon-level4',6,'6-7','Review of Levels 1-3 — comprehensive revision','Review all muttoon from Levels 1-3: Nawaaqid, Qawaid, Usool, Arba''in, Tuhfatul Atfaal, Shuruth, Tawheed, Bayquni, Ilbiri, Ajrumiyya, Wasitiyya.','mastery',5,'["verbal"]','["mt-002","mt-013","mt-018"]','all muttoon books'),
('mt-030','muttoon','muttoon-level4',6,'6-7','Memorization test — key passages','Test memorization of key passages from each muttoon: Nawaaqid, Tawheed, Arba''in, Ajrumiyya, Tahawiyya. Recite from memory with teacher verification.','mastery',3,'["verbal"]','["mt-029"]','teacher, assessment rubric')`);

  console.log('  Seeded 30 Muttoon topics (mt-001 to mt-030)');
}
