import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

export async function seedHomeScienceEnhanced() {
  const existing = await prisma.$queryRawUnsafe<{cnt: number}[]>(
    "SELECT COUNT(*) as cnt FROM \"CurriculumTopic\" WHERE subject='home-science' AND strand='hs-enhanced'"
  );
  const cnt = Number(existing[0]?.cnt ?? 1);
  if (cnt > 0) {
    console.log('  Home Science enhanced already seeded — skipping.');
    return;
  }
  console.log('  Seeding comprehensive Home Science expansion...');

  const s = 'home-science';
  const t = [
    // ═══════════════════════════════════════════════════════════
    // NUTRITION EXPANSION
    // ICSE Home Science, CBSE Home Science, Home Economics
    // ═══════════════════════════════════════════════════════════
    ['hse-001',s,'hs-enhanced',3,'3-4','Sugar Awareness: Sweet Traps','Many foods have hidden sugar: juice, yoghurt, cereal, ketchup. Too much sugar harms teeth and health. Learn to check labels, choose water over soda, and eat fruit instead of candy.','practice',2,'["hands-on"]','[""]','sugar cube display, label reading cards, healthy swap poster'],
    ['hse-002',s,'hs-enhanced',3,'3-4','Seasonal Eating and Local Food','Fruits and vegetables grow in seasons. Eating seasonal means fresher, cheaper, better for the environment. Learn what grows in spring, summer, autumn, winter in your region.','practice',2,'["visual"]','[""]','seasonal produce calendar, local farm visit activity'],
    ['hse-003',s,'hs-enhanced',4,'4-5','Food Allergies and Intolerances','Some people react badly to certain foods. Common allergens: nuts, milk, eggs, wheat, fish. Learn signs (rash, swelling, difficulty breathing), how to check labels, and how to keep friends with allergies safe.','practice',3,'["verbal"]','[""]','allergen awareness poster, safe food swap cards, label reading sheet'],
    ['hse-004',s,'hs-enhanced',4,'4-5','Traditional vs Processed Foods','Traditional: whole foods like rice, vegetables, meat cooked at home. Processed: packaged snacks, fast food, soda. Processed foods have more sugar, salt, and chemicals. Choose fresh and cook at home.','practice',2,'["visual"]','[""]','whole vs processed sort cards, homemade vs store-bought taste test'],
    ['hse-005',s,'hs-enhanced',4,'4-5','Healthy Snack Ideas','Snacks can be healthy: fruit, yoghurt, nuts, hummus with veggie sticks, dates, popcorn. Avoid chips, candy, sugary drinks. Make your own trail mix.','practice',2,'["hands-on"]','[""]','healthy snack recipe cards, snack prep activity, my snack plate chart'],
    ['hse-006',s,'hs-enhanced',4,'4-5','Expiry Dates and Food Storage','Best before vs use by: safety dates. Store food correctly: fridge for dairy and meat, cupboard for dry goods, freezer for long-term. Do not eat if moldy or smells off.','practice',2,'["hands-on"]','[""]','date checking activity, food storage poster, fridge organization sheet'],
    ['hse-007',s,'hs-enhanced',5,'5-6','Batch Cooking and Meal Prep','Cook in bulk: make extra rice, curry, or pasta sauce. Freeze portions for busy days. This saves time, money, and ensures healthy food is always available.','practice',2,'["hands-on"]','[""]','batch cooking recipe plan, freezer label sheet, portion guide'],
    ['hse-008',s,'hs-enhanced',5,'5-6','Understanding Food Labels: Nutrition Facts','Learn to read the back of packages: serving size, calories, sugar (total vs added), fat (saturated vs unsaturated), fibre, protein, ingredients list (first = most).','practice',3,'["hands-on"]','[""]','nutrition label guide, comparison worksheet, healthy choice activity'],
    ['hse-009',s,'hs-enhanced',5,'5-6','Herbs, Spices, and Sunnah Foods','Learn about halal spices: cumin, coriander, turmeric, black seed, ginger, saffron. Sunnah foods: dates, olives, honey, figs, barley, pomegranate. Each has health benefits mentioned in Quran and Hadith.','practice',3,'["hands-on"]','[""]','herbs and spice identification trays, sunnah foods poster, taste test'],
    ['hse-010',s,'hs-enhanced',5,'5-6','Drinks that Heal: Sunnah Beverages','Healthy drinks: water (best), milk, fresh juices, herbal teas. Sunnah drinks: Zamzam, honey water, barley water, milk with honey. Avoid: energy drinks, soda, excess caffeine.','practice',2,'["hands-on"]','[""]','beverage comparison chart, Sunnah drink recipe cards, taste testing'],

    // ═══════════════════════════════════════════════════════════
    // COOKING EXPANSION
    // ═══════════════════════════════════════════════════════════
    ['hse-011',s,'hs-enhanced',4,'4-5','Kitchen Appliances: Safe Use','Learn to use: microwave (reheat, defrost), blender (smoothies, soups), toaster, kettle. Rules: ask adult first, do not put metal in microwave, unplug after use, keep cords away from water.','practice',2,'["hands-on","verbal"]','[""]','appliance safety guide, use checklist, supervision reminder cards'],
    ['hse-012',s,'hs-enhanced',5,'5-6','Baking Basics: Cakes and Bread','Baking uses the oven. Learn: measure flour/sugar, mix wet and dry, grease the pan, set temperature safely with adult, check doneness with toothpick. Try simple banana bread or muffins.','practice',3,'["hands-on"]','[""]','baking measurement chart, simple recipes, step by step guide'],
    ['hse-013',s,'hs-enhanced',4,'4-5','Safe Cutting and Knife Skills','Use child-safe knives. Grip: hold food with claw hand, cut away from body. Chop: slice vegetables (cucumber, carrot), dice onions, mince garlic. Always cut on a chopping board.','practice',3,'["hands-on"]','[""]','child-safe knife, chopping board, veggie cutting guides'],
    ['hse-014',s,'hs-enhanced',5,'5-6','Food Presentation and Plating','Make food look beautiful: arrange colors, use garnish (parsley, herbs), serve in nice bowls. Eat with the right hand. Say Bismillah before eating. We eat with our eyes first.','practice',2,'["hands-on"]','[""]','plating inspiration cards, garnish ideas, Sunnah eating poster'],
    ['hse-015',s,'hs-enhanced',6,'6-7','International Cuisines: World Foods','Try dishes from different cultures: Arabic (hummus, falafel), Indian (dhal, rice), Italian (pasta, tomato sauce), Turkish (kebab, pide), Malay (nasi lemak, satay). Learn what is halal.','practice',3,'["hands-on"]','[""]','world map with food pins, recipe cards from 5 cuisines, taste passport'],
    ['hse-016',s,'hs-enhanced',5,'5-6','Meal Planning for the Week','Plan meals for 7 days: include breakfast, lunch, dinner, snacks. Balance food groups. Write a shopping list. Check what you already have. This saves money and reduces waste.','practice',2,'["hands-on"]','[""]','weekly meal plan template, shopping list pad, balanced meal guide'],
    ['hse-017',s,'hs-enhanced',5,'5-6','Grocery Shopping: Smart Choices','Make a list before shopping. Compare prices per unit. Choose fresh over packaged. Buy seasonal and local. Do not shop when hungry. Check expiry dates. Bring reusable bags.','practice',2,'["hands-on"]','[""]','shopping list template, price comparison game, smart shopper cards'],

    // ═══════════════════════════════════════════════════════════
    // FIRST AID & SAFETY EXPANSION
    // ═══════════════════════════════════════════════════════════
    ['hse-018',s,'hs-enhanced',4,'4-5','Sprains and Strains: RICE Method','If you twist an ankle or wrist: R = Rest (stop using it), I = Ice (wrap ice in cloth, apply 15 min), C = Compression (bandage gently), E = Elevate (raise above heart). Tell a grown-up.','practice',2,'["hands-on","verbal"]','[""]','RICE method poster, bandage practice, ice pack safety guide'],
    ['hse-019',s,'hs-enhanced',4,'4-5','Insect Bites and Stings','Bee stings, mosquito bites, ant bites. What to do: wash with soap and water, apply cold pack, put calamine lotion or antihistamine cream. If allergic (difficulty breathing), get emergency help.','practice',2,'["verbal"]','[""]','bite/sting identification cards, first aid step guide, emergency signs poster'],
    ['hse-020',s,'hs-enhanced',4,'4-5','Sun Safety and Heat Exhaustion','Sun protection: wear hat, sunglasses, sunscreen (SPF 50), stay in shade 11am-3pm. Drink water. Signs of heat exhaustion: headache, dizzy, hot/red skin, feel sick. Cool down and drink water.','practice',2,'["verbal","visual"]','[""]','sun safety poster, UV index chart, hydration tracker'],
    ['hse-021',s,'hs-enhanced',5,'5-6','First Aid Kit: What to Include','Your first aid kit: bandages (various sizes), gauze, medical tape, antiseptic wipes, scissors, tweezers, pain relief, antihistamine, burn cream, gloves, thermometer. Check expiry dates.','practice',3,'["hands-on"]','[""]','first aid kit box, inventory checklist, item function cards'],
    ['hse-022',s,'hs-enhanced',5,'5-6','The Recovery Position','If someone is unconscious but breathing: roll them on their side, tilt head back, bend top knee for stability, monitor breathing. Call emergency services. Do NOT move if spinal injury suspected.','practice',2,'["hands-on"]','[""]','recovery position poster, practice mat, steps checklist'],
    ['hse-023',s,'hs-enhanced',5,'5-6','Fainting and Dizziness','If you feel faint: sit down, put head between knees, breathe slowly. If someone faints: lay them flat, raise legs, loosen tight clothing, check breathing, call adult.','practice',2,'["verbal"]','[""]','faint signs cards, response steps poster, buddy system guide'],
    ['hse-024',s,'hs-enhanced',5,'5-6','Poisoning Awareness','Never eat or drink something from an unlabeled container. Cleaning products, medicine, and batteries are dangerous. If someone swallows poison: call emergency, do not make them vomit, bring the container.','practice',2,'["verbal","visual"]','[""]','poisonous household items cards, Mr Yuk stickers, emergency guide'],
    ['hse-025',s,'hs-enhanced',6,'6-7','Basic Hygiene: Preventing Illness','Wash hands: before eating, after toilet, after coughing/sneezing, after touching animals. Cough into elbow. Do not share cups or utensils. Brush teeth twice a day. Shower daily.','practice',4,'["hands-on"]','[""]','handwashing steps poster, hygiene checklist, toothbrushing chart'],
    ['hse-026',s,'hs-enhanced',6,'6-7','Fire Safety and Smoke Alarms','Know your smoke alarm. Test it monthly. If fire: get low, crawl under smoke, feel door before opening, have an escape plan, meet outside. Never hide from fire. Know emergency number.','practice',2,'["verbal","hands-on"]','[""]','escape plan template, smoke alarm test chart, fire drill checklist'],
    ['hse-027',s,'hs-enhanced',6,'6-7','Electrical Safety at Home','Electricity and water do not mix. Do not put fingers or objects in sockets. Do not pull cords by the wire. Unplug when not in use. Keep cords away from pets and toddlers.','practice',2,'["verbal","visual"]','[""]','electrical safety poster, socket covers, hazard identification game'],

    // ═══════════════════════════════════════════════════════════
    // HOUSEHOLD & HOME MANAGEMENT EXPANSION
    // ═══════════════════════════════════════════════════════════
    ['hse-028',s,'hs-enhanced',3,'3-4','Organizing Your Room: Decluttering','A tidy room helps you think clearly. Sort toys into: keep, donate, trash. Use boxes for different toys. Make your bed every morning. Put clothes in the wardrobe. Everything has its place.','practice',2,'["hands-on"]','[""]','organizing bins and labels, room checklist sticker chart, tidy-up timer'],
    ['hse-029',s,'hs-enhanced',4,'4-5','Recycling and Waste Management','Reduce, reuse, recycle. Separate waste: paper, plastic, glass, metal, food waste. Composting: food scraps for garden. Learn what goes in each bin. The Prophet said: Cleanliness is half of faith.','practice',2,'["hands-on"]','[""]','recycling bin labels, compost guide, waste sorting game'],
    ['hse-030',s,'hs-enhanced',4,'4-5','Pet Care Basics','If you have a pet: feed daily, provide clean water, keep their area clean, exercise them, take to vet. Do not be cruel. The Prophet said: Whoever is kind to animals will be rewarded.','practice',2,'["hands-on"]','[""]','pet care checklist, animal kindness hadith cards, responsibility chart'],
    ['hse-031',s,'hs-enhanced',4,'4-5','Plant and Garden Care','Plants need: sunlight, water (not too much), soil, and air. Learn to water indoor plants, pull weeds, plant seeds. Growing your own food (herbs, vegetables) teaches patience and responsibility.','practice',3,'["hands-on"]','[""]','seed packets, watering schedule chart, plant growth diary'],
    ['hse-032',s,'hs-enhanced',4,'4-5','Caring for Younger Siblings','Help with: fetching diapers, entertaining baby, reading to them, keeping them safe. Be gentle and patient. The Prophet was kind to children. Babies are a trust from Allah.','practice',2,'["hands-on"]','[""]','sibling helper checklist, baby safety cards, patience tips'],
    ['hse-033',s,'hs-enhanced',5,'5-6','Money Management: Allowance and Saving','Learn: income (allowance, gifts), spending (wants vs needs), saving. Use three jars: Save (for goals), Spend (everyday), Give (charity). The Prophet said: The upper hand (giving) is better than the lower hand.','practice',3,'["hands-on"]','[""]','three jars labels, savings goal chart, budget practice sheet'],
    ['hse-034',s,'hs-enhanced',5,'5-6','Time Management: Daily Routine','Plan your day: Fajr prayer, school, homework, play, chores, family time, sleep. Use a visual schedule. Do important things first. The Prophet organized his time between worship, family, and community.','practice',3,'["hands-on"]','[""]','daily schedule template, routine cards, clock practice sheet'],
    ['hse-035',s,'hs-enhanced',5,'5-6','Packing Your Own School Bag','Pack your bag the night before: books, lunchbox, water bottle, completed homework, school letters. Check timetable. Do not bring toys or unnecessary items. Responsibility and organization.','practice',2,'["hands-on"]','[""]','packing checklist, timetable card, organization sticker chart'],
    ['hse-036',s,'hs-enhanced',5,'5-6','Dish Washing and Kitchen Clean-Up','Scrape food off plates, wash with warm soapy water, rinse, dry, put away. Wash in order: glasses first, then plates, then pots. Wipe counter after. Dry with clean towel.','practice',2,'["hands-on"]','[""]','dish washing steps poster, drying cloth, clean-up checklist'],
    ['hse-037',s,'hs-enhanced',5,'5-6','Hospitality: Hosting Guests in Islam','When guests come: smile, welcome them, offer food/drink first. The Prophet said: Whoever believes in Allah let him honor his guest. Help prepare the house. Offer the best seat. See them out.','practice',2,'["hands-on"]','[""]','hospitality hadith cards, hosting checklist, guest welcome sheet'],
    ['hse-038',s,'hs-enhanced',5,'5-6','Clothing Care: Folding and Stain Removal','Fold clothes properly (shirt, pants, socks). Sort by type. Remove stains early: cold water for blood, warm for grease, lemon for fruit. Use spot remover. Learn basic ironing with adult help.','practice',3,'["hands-on"]','[""]','folding technique guide, stain removal chart, laundry routine poster'],
    ['hse-039',s,'hs-enhanced',6,'6-7','Simple DIY: Light Repairs at Home','Learn to: change a lightbulb safely (adult supervision), tighten a loose screw, fix a sticking door, replace batteries in remote. Know where the fuse box and water shut-off are.','practice',2,'["hands-on"]','[""]','tool set (screwdriver, pliers), repair guide cards, safety checklist'],
    ['hse-040',s,'hs-enhanced',6,'6-7','Hosting a Meal: From Plan to Clean-Up','Plan a full meal: choose a recipe, make a shopping list, buy ingredients, cook, set the table, serve, eat, and clean up. Work as a team. Hosting is a form of worship in Islam.','practice',4,'["hands-on"]','[""]','meal planning template, shopping list pad, hosting timeline cards'],
    ['hse-041',s,'hs-enhanced',6,'6-7','Cleaning Different Surfaces','Learn what cleaner to use: glass cleaner for windows, gentle soap for wood, vinegar and baking soda for natural cleaning. Microfiber cloths work best. Do not mix bleach with ammonia (toxic gas).','practice',2,'["hands-on"]','[""]','cleaning supplies guide, surface sorting cards, natural cleaner recipes'],
    ['hse-042',s,'hs-enhanced',6,'6-7','Emergency Preparedness: Home Safety','Know: where the first aid kit is, emergency numbers, fire blanket/extinguisher location, how to shut off gas/water. Have a family emergency plan. Practice drills.','practice',2,'["verbal","hands-on"]','[""]','emergency plan template, numbers card, checklist poster'],
    ['hse-043',s,'hs-enhanced',6,'6-7','Water Conservation at Home','Turn off tap while brushing teeth. Take shorter showers. Collect rainwater for plants. Fix dripping taps. Every drop is a blessing from Allah. He made from water every living thing.','practice',2,'["hands-on"]','[""]','water saving checklist, Quran verses on water, conservation poster'],
    ['hse-044',s,'hs-enhanced',6,'6-7','Basic Sewing: Buttons and Hems','Thread a needle (use needle threader). Tie a knot. Sew a button (cross or parallel). Fix a small tear with running stitch. Basic mending saves money and reduces waste.','practice',3,'["hands-on"]','[""]','sewing kit (needles, thread, buttons), practice cloth, step-by-step guide'],
    ['hse-045',s,'hs-enhanced',6,'6-7','Food Preservation: Freezing and Drying','Preserve food to reduce waste: freeze leftovers, dry herbs, pickle vegetables, make jam. Learn which foods freeze well (bread, meat, sauce) and which do not (lettuce, eggs in shell).','practice',2,'["hands-on"]','[""]','freezer guide chart, herb drying rack, pickling recipe card'],
    ['hse-046',s,'hs-enhanced',5,'5-6','Tidying Common Areas: Living Room and Yard','Help keep shared spaces clean: fluff cushions, fold blankets, sweep floor, water plants, pick up litter in the yard. Teamwork makes home beautiful for everyone.','practice',2,'["hands-on"]','[""]','cleaning rotation chart, shared space checklist, family helper cards'],
    ['hse-047',s,'hs-enhanced',3,'3-4','Habit Stacking: Building Healthy Routines','Link new habits to existing ones: brush teeth after Fajr, pack bag after dinner, read Quran after Maghrib. Small habits done daily become strong. Consistency is key.','practice',3,'["hands-on"]','[""]','habit tracker chart, habit stacking cards, routine stickers'],
    ['hse-048',s,'hs-enhanced',5,'5-6','Clothing Selection: Dressing Modestly and Practically','Choose comfortable, modest, weather-appropriate clothes. Understand Islamic dress principles. Learn what to wear for different activities (school, play, masjid, sports). Take care of your clothes.','practice',2,'["verbal","visual"]','[""]','dress code cards, weather-based clothing chart, modesty poster'],
    ['hse-049',s,'hs-enhanced',4,'4-5','Forgiveness and Letting Go of Mistakes','When you make a mistake: say Astaghfirullah, learn from it, try again. Allah is Al-Ghafur (The Forgiving). Do not dwell on failures. Talk to someone you trust. Every mistake is a chance to grow.','practice',3,'["verbal","hands-on"]','[""]','forgiveness cards, growth mindset poster, error to effort activity'],
    ['hse-050',s,'hs-enhanced',5,'5-6','Using Your Phone and Tablet Responsibly','Set screen time limits. Keep devices in common areas. No devices at mealtimes or before bed. Ask permission before downloading. Be kind online. Do not share personal information.','practice',3,'["verbal","hands-on"]','[""]','screen time chart, digital agreement form, tech-free activity list'],
  ];

  for (let i = 0; i < t.length; i += 5) {
    const batch = t.slice(i, i + 5);
    const values = batch.map(r =>
      `('${r[0]}','${r[1]}','${r[2]}',${r[3]},'${r[4]}','${r[5]}','${r[6]}','${r[7]}',${r[8]},'${r[9]}','${r[10]}','${r[11]}')`
    ).join(',');
    await prisma.$executeRawUnsafe(
      `INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES ${values}`
    );
    console.log(`  Home Sci Batch ${Math.floor(i/5)+1}: topics ${i+1}-${Math.min(i+5,t.length)}`);
  }
  console.log(`  Seeded ${t.length} Home Science topics`);
}
