import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

export async function seedSeerahEnhanced() {
  const existing = await prisma.$queryRawUnsafe<{cnt: number}[]>(
    "SELECT COUNT(*) as cnt FROM \"CurriculumTopic\" WHERE subject='islamic-studies' AND strand='seerah-enhanced'"
  );
  const cnt = Number(existing[0]?.cnt ?? 1);
  if (cnt > 0) {
    console.log('  Seerah enhanced already seeded — skipping.');
    return;
  }
  console.log('  Seeding comprehensive Seerah expansion...');

  const s = 'islamic-studies';
  const t = [
    // ═══════════════════════════════════════════════════════════
    // PRE-PROPHETHOOD & EARLY LIFE EXPANSION
    // Based on: Ibn Ishaq, Ibn Hisham, Ibn Kathir's Seerah
    // ═══════════════════════════════════════════════════════════
    ['is-see01',s,'seerah-enhanced',2,'2-3','The Year of the Elephant','In the year the Prophet was born, Abrahah attacked Makkah with elephants. Allah sent flocks of birds with stones of baked clay, destroying them. Allah protected His House. (Quran 105)','practice',2,'["verbal","visual"]','[""]','elephant story cards, Ababil bird drawing'],
    ['is-see02',s,'seerah-enhanced',3,'3-4','The Prophet Marries Khadijah','At 25, the Prophet married Khadijah bint Khuwaylid, a wealthy and noble businesswoman. She proposed to him after being impressed by his honesty. She was his first and only wife for 25 years.','practice',2,'["verbal"]','[""]','Khadijah character poster, seerah timeline'],
    ['is-see03',s,'seerah-enhanced',3,'3-4','The Prophet Travels to Syria for Trade','The Prophet went with Khadijahs caravan to Syria. A monk named Bahira recognized the seal of prophethood and said: This is the Messenger of the Lord of the Worlds waiting for him.','practice',2,'["verbal","visual"]','[""]','trade route map, Bahira meeting illustration'],
    ['is-see04',s,'seerah-enhanced',3,'3-4','Rebuilding the Kabah: The Black Stone','When the Kabah was rebuilt, the tribes argued over who would place the Black Stone. Young Muhammad suggested putting it on a cloth and having all tribal leaders carry it together. His wisdom prevented war.','practice',2,'["verbal","visual"]','[""]','black stone story cards, conflict resolution lesson'],
    ['is-see05',s,'seerah-enhanced',3,'3-4','The Prophet in Cave Hira','Before revelation, the Prophet would spend days in Cave Hira on Mount Nur, thinking about Allahs creation and the corruption in Makkah. He would take food and return to Khadijah.','introduction',2,'["verbal","visual"]','[""]','Hira cave picture, reflection activity'],
    ['is-see06',s,'seerah-enhanced',4,'4-5','The Children of the Prophet','The Prophet had 7 children: 3 sons (Qasim, Abdullah, Ibrahim) and 4 daughters (Zainab, Ruqayyah, Umm Kulthum, Fatimah). All sons died in infancy. Fatimah survived him by 6 months. He loved them dearly.','practice',2,'["verbal","visual"]','[""]','Prophets family tree poster, children cards'],

    // ═══════════════════════════════════════════════════════════
    // MAKKAH PERIOD EXPANSION
    // Isra wal-Mi'raj, Ta'if, Aqabah, Year of Sorrow
    // ═══════════════════════════════════════════════════════════
    ['is-see07',s,'seerah-enhanced',5,'5-6','Isra and Miraj: The Night Journey','The Prophet was taken from the Sacred Mosque in Makkah to the Aqsa Mosque in Jerusalem in one night. From there he ascended to the heavens. Allah gave him the gift of 5 daily prayers. (Quran 17:1, 53:13-18)','practice',4,'["verbal","visual"]','[""]','Isra and Miraj poster, al-Buraq coloring, 7 heavens chart'],
    ['is-see08',s,'seerah-enhanced',5,'5-6','The Journey to Taif','After Khadijah and Abu Talib died, the Prophet went to Taif to invite them to Islam. They rejected him, threw stones at him, and made him bleed. The angel of mountains asked: Should I destroy them? The Prophet said: No, maybe their children will believe.','practice',2,'["verbal","visual"]','[""]','Taif journey map, forgiveness story illustration'],
    ['is-see09',s,'seerah-enhanced',5,'5-6','The Year of Sorrow (Am al-Huzn)','In one terrible year, the Prophet lost his beloved wife Khadijah and his uncle Abu Talib. Khadijah was his comfort and supporter. Abu Talib protected him from the Quraysh despite not accepting Islam.','practice',2,'["verbal"]','["se-027"]','Year of Sorrow poster, patience lesson'],
    ['is-see10',s,'seerah-enhanced',4,'4-5','The Second Pledge of Aqabah','A year after the first pledge, 73 men and 2 women from Madinah pledged to protect the Prophet as they protect their own families. This led to the Hijrah. The Prophet sent Musab ibn Umayr to teach them Quran first.','practice',3,'["verbal"]','[""]','Aqabah pledge cards, Ansar loyalty story'],
    ['is-see11',s,'seerah-enhanced',5,'5-6','The First Pledge of Aqabah','12 men from Madinah came to the Prophet at Aqabah. They pledged: not to worship anyone besides Allah, not to steal or commit adultery, not to kill their children, and to obey the Prophet in good.','practice',2,'["verbal"]','["is-see10"]','pledge conditions poster, Madinah preparation story'],

    // ═══════════════════════════════════════════════════════════
    // MADINAH PERIOD EXPANSION
    // Constitution, Jewish tribes, Wives, Delegations
    // ═══════════════════════════════════════════════════════════
    ['is-see12',s,'seerah-enhanced',5,'5-6','The Constitution of Madinah','The Prophet wrote a constitution uniting the Muhajireen, Ansar, Jews, and others in Madinah. It guaranteed religious freedom, mutual protection, and justice for all citizens. This was the first written constitution in history.','practice',3,'["verbal","visual"]','[""]','constitution summary cards, equality lesson'],
    ['is-see13',s,'seerah-enhanced',5,'5-6','The Prophet Pairs the Companions as Brothers','The Prophet paired each Muhajir with an Ansari brother. They shared homes, wealth, and inheritance. The Ansar gave half their property. This brotherhood was stronger than blood ties.','practice',2,'["hands-on"]','["se-030"]','brotherhood pairs poster, sharing activity'],
    ['is-see14',s,'seerah-enhanced',5,'5-6','The Wives of the Prophet (Ummahat al-Mumineen)','The Prophets wives are our Mothers. Khadijah (1st, died in Makkah). Aisha (scholar, teacher), Hafsah (knower of Quran), Umm Salamah (wise), Sawdah, Zaynab, Juwayriyyah, Umm Habibah, Safiyyah, Maymunah. Learn their virtues.','practice',3,'["verbal","visual"]','[""]','Ummahat al-Mumineen poster, wives virtues cards'],
    ['is-see15',s,'seerah-enhanced',6,'6-7','Umm Salamah: The Wise Wife','Umm Salamah was known for her wisdom. During the Treaty of Hudaybiyyah, when the companions were sad, she advised the Prophet to sacrifice his animal and shave, which made the companions follow.','practice',2,'["verbal"]','["is-see14"]','Umm Salamah wisdom story, problem solving lesson'],
    ['is-see16',s,'seerah-enhanced',5,'5-6','Aisha: The Mother of Scholars','Aisha was the most knowledgeable woman in Islamic history. She narrated thousands of hadith. She taught Quran, fiqh, medicine, and poetry. The Prophet said: Learn half your religion from this red-haired woman.','practice',2,'["verbal"]','["is-see14"]','Aisha virtues cards, female scholarship lesson'],
    ['is-see17',s,'seerah-enhanced',6,'6-7','Banu Qaynuqa: The First Broken Treaty','The Jewish tribe of Banu Qaynuqa broke the Madinah constitution and attacked a Muslim woman. After a siege of 15 days, they surrendered. The Prophet exiled them from Madinah.','practice',2,'["verbal"]','[""]','treaty violations lesson, justice role-play'],
    ['is-see18',s,'seerah-enhanced',6,'6-7','Banu Nadir and Banu Qurayzah','Banu Nadir broke the treaty and planned to kill the Prophet. They were exiled. Banu Qurayzah allied with the Quraysh during Khandaq and were dealt with according to their own law (Saad ibn Muadh ruling).','practice',3,'["verbal"]','["is-see17"]','Jewish tribes timeline, Saad ibn Muadh story'],
    ['is-see19',s,'seerah-enhanced',6,'6-7','The Year of Delegations (Sanat al-Wufud)','After the conquest of Makkah, tribes from all over Arabia came to Madinah to accept Islam. The Prophet was kind and patient with everyone. He taught them the Quran and sent teachers with them.','practice',2,'["verbal"]','[""]','delegations map, tribes of Arabia poster'],
    ['is-see20',s,'seerah-enhanced',6,'6-7','Expedition of Tabuk','The largest expedition. 30,000 Muslims marched to face the Romans. The hypocrites made excuses to stay behind. The journey was very hard (scorching heat, little water). The Romans did not attack. Quran revealed about the hypocrites.','practice',3,'["verbal","visual"]','[""]','Tabuk map, Uthmans generosity story, hypocrite signs'],

    // ═══════════════════════════════════════════════════════════
    // BATTLES EXPANSION (Detailed study for older children)
    // Based on: Ibn Kathir, Seerah books
    // ═══════════════════════════════════════════════════════════
    ['is-see21',s,'seerah-enhanced',5,'5-6','Battle of Badr: Detailed Study','Badr was on 17 Ramadan 2 AH. The Muslims wanted to intercept a trade caravan but ended up facing the Quraysh army. Key events: the Prophet making dua, Allah sending rain, angels helping, 313 vs 1000. Lessons: trust Allah, take means.','practice',4,'["verbal","visual"]','[""]','Badr battle map, key figures cards, Quran verses (3:123-125)'],
    ['is-see22',s,'seerah-enhanced',5,'5-6','Battle of Uhud: The Archers Disobey','The Prophet placed 50 archers on a hill and ordered them: Do not leave your position even if you see us winning. When the Muslims started winning, the archers left. The Quraysh cavalry attacked from behind. Hamza was martyred.','practice',4,'["verbal","visual"]','[""]','Uhud map, archers story, Hamza martyrdom, lessons on obedience'],
    ['is-see23',s,'seerah-enhanced',5,'5-6','Battle of the Trench (Khandaq)','In 5 AH, 10,000 enemy soldiers surrounded Madinah. Salman al-Farsi suggested digging a trench. The siege lasted 20-30 days. The Confederates could not cross. Allah sent a windstorm and they fled. (Quran 33:9-27)','practice',3,'["verbal","hands-on"]','[""]','trench model activity, Salman story, Quran lesson'],
    ['is-see24',s,'seerah-enhanced',6,'6-7','Battle of Khaybar','In 7 AH, the Muslim army of 1400 marched to Khaybar where the Jews had fortified themselves. Ali ibn Abi Talib famously conquered the fortress. The Muslims gained resources and the Jews were allowed to stay and farm.','practice',2,'["verbal","visual"]','[""]','Khaybar fortress, Ali bravery story, Khaybar map'],
    ['is-see25',s,'seerah-enhanced',6,'6-7','Conquest of Makkah: The Greatest Victory','In 8 AH, 10,000 Muslims marched to Makkah. Abu Sufyan embraced Islam. The Prophet entered Makkah humbly bowing on his camel. He forgave everyone: Go, you are free. He cleared the Kabah of idols.','practice',4,'["verbal","visual"]','[""]','conquest map, forgiveness story, Kabah cleansing activity'],
    ['is-see26',s,'seerah-enhanced',6,'6-7','Battle of Hunayn and the Siege of Taif','After Makkah, the Hawazin tribe fought at Hunayn. The Muslims initially panicked but rallied around the Prophet. Many prisoners were freed. The Prophet distributed the spoils generously to new Muslims.','practice',2,'["verbal"]','[""]','Hunayn story, generosity lesson, Taif map'],
    ['is-see27',s,'seerah-enhanced',5,'5-6','Expedition of Banu Mustaliq and the Ifk Incident','After Banu Mustaliq surrendered, the hypocrites spread lies (Ifk) about Aisha. Allah revealed 10 verses of Surah Nur (24:11-20) clearing her name. This teaches us to avoid rumors and trust Allah.','practice',3,'["verbal"]','[""]','Ifk lesson cards, Quran 24:11-20 study, gossip awareness'],

    // ═══════════════════════════════════════════════════════════
    // THE PROPHET'S CHARACTER EXPANSION
    // Based on: Shama'il al-Muhammadiyyah
    // ═══════════════════════════════════════════════════════════
    ['is-see28',s,'seerah-enhanced',4,'4-5','The Physical Description of the Prophet','The Prophet was of medium height, not tall or short. He had a beautiful face that shone like the moon. His hair was neither curly nor straight. He had a thick beard. His walk was swift and purposeful.','practice',2,'["verbal","visual"]','[""]','Shamail cards, Prophet description poster'],
    ['is-see29',s,'seerah-enhanced',4,'4-5','The Prophet Generosity','The Prophet was the most generous person, especially in Ramadan. He gave like the wind. He never turned away a beggar. Once he gave a man so many sheep that they filled the valley between two mountains.','practice',2,'["verbal","hands-on"]','[""]','generosity challenge, Prophet giving story'],
    ['is-see30',s,'seerah-enhanced',4,'4-5','The Prophet Courage and Bravery','The Prophet was the bravest of people. At Badr, he stood firm. At Uhud, when the companions fled, he stayed. Ali said: When the battle was fierce, we would take shelter behind the Messenger of Allah.','practice',2,'["verbal"]','[""]','courage story cards, bravery in faith lesson'],
    ['is-see31',s,'seerah-enhanced',4,'4-5','The Prophet Humility','The Prophet lived humbly: he patched his own clothes, milked his own goats, ate on the floor, and sat with the poor. He did not like people standing up for him. He rode a donkey and carried his own baggage.','practice',2,'["verbal","hands-on"]','[""]','humility checklist, Prophet simple living story'],
    ['is-see32',s,'seerah-enhanced',5,'5-6','The Prophet Compassion and Mercy','The Prophet was merciful to everyone: children, old people, women, animals, prisoners, and even enemies. He visited the sick, comforted the sad, and played with children. He said: Show mercy and you will receive mercy.','practice',2,'["verbal"]','[""]','mercy activity cards, Prophet kindness examples'],
    ['is-see33',s,'seerah-enhanced',5,'5-6','The Prophet Justice','The Prophet was just with everyone, even with non-Muslims. He said: If Fatimah (my own daughter) stole, I would cut off her hand. He judged fairly between people and never favored family over truth.','practice',2,'["verbal"]','[""]','justice stories, fair decision activity'],
    ['is-see34',s,'seerah-enhanced',5,'5-6','The Prophet Patience','The Prophet was patient through: being orphaned, poverty, losing children, rejection, torture of companions, hunger, illness, and the death of loved ones. He never complained to Allah. He said: Patience is light.','practice',2,'["verbal"]','[""]','patience timeline, hardship cards, sabr lesson'],
    ['is-see35',s,'seerah-enhanced',5,'5-6','The Prophet Worship and Devotion','The Prophet prayed at night until his feet swelled. He fasted Mondays and Thursdays. He made dhikr constantly. He read Quran daily. He loved to pray. He said: The coolness of my eyes is in the prayer.','practice',3,'["verbal","hands-on"]','[""]','Prophet ibadah tracker, night prayer motivation'],
    ['is-see36',s,'seerah-enhanced',5,'5-6','The Prophet Duas for Every Occasion','The Prophet taught us duas for everything: waking up, sleeping, eating, drinking, leaving home, entering home, sneezing, rain, traveling, new clothes, visiting sick, and more. Over 100 daily duas.','practice',4,'["hands-on"]','[""]','fortress of Muslim cards, dua poster, practice book'],
    ['is-see37',s,'seerah-enhanced',5,'5-6','The Prophet Treatment of Women','The Prophet honored women: He helped his wives with housework. He stood up when his daughter Fatimah entered. He taught men to treat their wives with kindness. He said: The best of you is the best to his family.','practice',2,'["verbal"]','[""]','women in Islam poster, Prophet family life stories'],
    ['is-see38',s,'seerah-enhanced',5,'5-6','The Prophet and the Poor','The Prophet lived in poverty and loved the poor. He shared their simple food. He visited them when sick. He said: O Allah, keep me poor and let me die among the poor. He fed the hungry and clothed the naked.','practice',2,'["verbal","hands-on"]','[""]','feeding the poor activity, Prophet poverty story'],

    // ═══════════════════════════════════════════════════════════
    // COMPANIONS EXPANSION
    // Key companions with detailed stories
    // ═══════════════════════════════════════════════════════════
    ['is-see39',s,'seerah-enhanced',4,'4-5','The Ten Companions Promised Paradise','The Prophet gave glad tidings of Paradise to 10 companions: Abu Bakr, Umar, Uthman, Ali, Talhah, Zubayr, Abdur-Rahman ibn Awf, Saad ibn Abi Waqqas, Saeed ibn Zayd, Abu Ubaydah ibn al-Jarrah.','practice',2,'["verbal","visual"]','[""]','10 promised Paradise poster, companion cards'],
    ['is-see40',s,'seerah-enhanced',5,'5-6','Khadijah: The First Believer','Khadijah was the first to believe. She comforted the Prophet when revelation came. She spent all her wealth for Islam. The Prophet said: She believed in me when everyone rejected me. Jibril told him to give her salam and glad tidings of a palace in Paradise.','practice',3,'["verbal"]','["is-see02"]','Khadijah virtues poster, first believer story'],
    ['is-see41',s,'seerah-enhanced',5,'5-6','Fatimah: The Leader of the Women of Paradise','Fatimah was the Prophets favourite daughter. She helped her father, was patient in poverty, and was the mother of Hasan and Husayn. The Prophet said: Fatimah is the leader of the women of Paradise.','practice',2,'["verbal"]','["is-see06"]','Fatimah story, women role models poster'],
    ['is-see42',s,'seerah-enhanced',5,'5-6','Hasan and Husayn: The Prophets Grandsons','Hasan and Husayn were the Prophets beloved grandsons. He would play with them, carry them on his shoulders, and kiss them. The Prophet said: Hasan and Husayn are the leaders of the youth of Paradise.','practice',2,'["verbal","hands-on"]','["is-see41"]','grandsons story, love for Ahlul-Bayt lesson'],
    ['is-see43',s,'seerah-enhanced',6,'6-7','Musab ibn Umayr: The First Ambassador','Musab was a wealthy young man who left everything for Islam. He was sent to Madinah to teach Quran. He was the first ambassador of Islam. He was martyred at Uhud with so little cloth that they covered his head and his feet showed.','practice',2,'["verbal","visual"]','[""]','Musab story, sacrifice lesson, dawah cards'],
    ['is-see44',s,'seerah-enhanced',5,'5-6','Abdullah ibn Abbas: The Scholar of the Ummah','Ibn Abbas was the Prophets cousin, only 13 when the Prophet died. The Prophet made dua: O Allah, give him knowledge of the religion and teach him the interpretation of the Quran. He became the greatest scholar of Quran.','practice',2,'["verbal"]','[""]','Ibn Abbas story, seeking knowledge lesson'],
    ['is-see45',s,'seerah-enhanced',5,'5-6','Abdullah ibn Umar: The Follower of Sunnah','Ibn Umar tried to follow the Prophet in everything. If he saw the Prophet do something, he would do it. If he saw the Prophet pray under a tree, he would pray there. He was known for his piety and knowledge.','practice',2,'["verbal"]','[""]','Ibn Umar sunnah following story, devotion lesson'],
    ['is-see46',s,'seerah-enhanced',5,'5-6','Saad ibn Abi Waqqas: The Arrow of Islam','Saad was the first to shoot an arrow for Islam. He was one of the 10 promised Paradise. His mother tried to stop him by starving herself, but he said: Even if you had a thousand souls, I would not leave Islam.','practice',2,'["verbal"]','[""]','Saad story, parents vs faith lesson, bravery card'],
    ['is-see47',s,'seerah-enhanced',6,'6-7','The Ansar: The Helpers of Madinah','The Ansar welcomed the Muhajireen, shared their homes, and preferred others over themselves. Allah praised them in the Quran (59:9). They loved the Prophet more than their own families. They are our role models in hospitality.','practice',2,'["verbal","hands-on"]','[""]','Ansar loyalty story, hospitality activity, sharing challenge'],
    ['is-see48',s,'seerah-enhanced',6,'6-7','The Muhajireen: Those Who Left Everything','The Muhajireen left their homes, families, and wealth in Makkah for Allah. They started with nothing in Madinah. The Prophet said about them: They left their homes seeking My pleasure. Their reward is with Allah.','practice',2,'["verbal"]','[""]','Muhajireen sacrifice story, emigration lesson'],
    ['is-see49',s,'seerah-enhanced',5,'5-6','Sumayyah, Yasir, and Ammar: The First Martyrs','Sumayyah was the first martyr in Islam. Ammar and his parents Yasir and Sumayyah were tortured by the Quraysh. The Prophet would pass by them and say: Be patient, family of Yasir. Paradise is waiting for you.','practice',2,'["verbal"]','[""]','Sumayyah courage story, persecution lesson, first martyr cards'],
    ['is-see50',s,'seerah-enhanced',5,'5-6','Zayd ibn Harithah: The Beloved','Zayd was the Prophets adopted son and freed slave. The Prophet loved him deeply. He led expeditions and was martyred at the Battle of Mutah. The Prophet cried when he heard the news.','practice',2,'["verbal"]','[""]','Zayd story, adopted son, leadership lesson'],
    ['is-see51',s,'seerah-enhanced',6,'6-7','Khalid ibn al-Walid: The Sword of Allah','Khalid was a great general who accepted Islam after Hudaybiyyah. The Prophet named him Saifullah (Sword of Allah). He never lost a battle. He led the conquests of Persia and Syria.','practice',2,'["verbal","visual"]','[""]','Khalid story, military map, bravery lesson'],
    ['is-see52',s,'seerah-enhanced',6,'6-7','Abu Ubaydah ibn al-Jarrah: The Trustworthy','The Prophet said: Every Ummah has a trustworthy one, and the trustworthy of this Ummah is Abu Ubaydah. He led the army in Syria. He was gentle, humble, and honest.','practice',2,'["verbal"]','[""]','Abu Ubaydah story, trustworthiness lesson'],

    // ═══════════════════════════════════════════════════════════
    // PROPHETS STORIES EXPANSION
    // Additional prophets for older children
    // ═══════════════════════════════════════════════════════════
    ['is-see53',s,'seerah-enhanced',4,'4-5','Prophet Adam: The First Human and Prophet','Allah created Adam from clay and taught him all the names. The angels prostrated to Adam, but Iblis refused. Adam and Hawwa lived in Paradise but were tricked by shaytan. Allah forgave them. (Quran 2:30-39)','practice',3,'["verbal","visual"]','[""]','Adam creation story, repentance lesson, iblees warning'],
    ['is-see54',s,'seerah-enhanced',4,'4-5','Prophet Yusuf: Patience and Forgiveness','Yusuf was thrown in a well, sold as a slave, imprisoned, and tested with temptation. He remained patient and trusted Allah. Eventually he became a minister in Egypt and forgave his brothers. The most beautiful story in the Quran.','practice',3,'["verbal","visual"]','[""]','Yusuf story cards, patience lesson, forgiveness activity'],
    ['is-see55',s,'seerah-enhanced',5,'5-6','Prophet Musa: The One Who Spoke to Allah','Musa faced Pharaoh, the most powerful tyrant. Allah gave him miracles: the staff turning into a snake, the hand shining white. He split the sea with his staff. Allah gave him the Torah. (Quran 20:9-98, 28:3-46)','practice',3,'["verbal","visual"]','[""]','Musa story timeline, 10 plagues, splitting the sea activity'],
    ['is-see56',s,'seerah-enhanced',5,'5-6','Prophet Ibrahim: The Friend of Allah','Ibrahim smashed the idols, was thrown in a fire that became cool, was tested by sacrificing his son, built the Kabah, and taught us the Hajj rituals. He is called Khalilullah (Friend of Allah). (Quran 21:51-73, 37:99-113)','practice',3,'["verbal","visual"]','[""]','Ibrahim story pack, fire/ cool story, sacrifice lesson'],
    ['is-see57',s,'seerah-enhanced',5,'5-6','Prophet Nuh: The Patient Caller','Nuh called his people for 950 years. Only about 80 believed. He built the ark under Allahs guidance. The flood covered the earth. Nuh, the believers, and animals were saved. (Quran 11:25-49, 71:1-28)','practice',2,'["verbal","visual"]','[""]','Nuh story cards, ark model activity, patience lesson'],
    ['is-see58',s,'seerah-enhanced',5,'5-6','Prophet Isa: The Miracle of Allah','Isa was born without a father by Allahs power. He spoke as a baby. He cured the blind and lepers, raised the dead by Allahs permission. He was not killed but raised to heaven. He will return before the Day of Judgment. (Quran 3:45-59, 4:157-159)','practice',3,'["verbal","visual"]','[""]','Isa miracles cards, his return poster, Quranic evidence'],
    ['is-see59',s,'seerah-enhanced',5,'5-6','Prophet Yunus: The Man in the Whale','Yunus became frustrated with his people and left without Allahs permission. He was swallowed by a big fish. In the darkness (3 darknesses: night, sea, fish belly), he called: La ilaha illa Anta, Subhanaka, inni kuntu min al-zalimeen. Allah forgave him.','practice',2,'["verbal","visual"]','[""]','Yunus dua poster, repentance lesson, whale story illustration'],
    ['is-see60',s,'seerah-enhanced',5,'5-6','Prophet Ayyub: The Model of Patience','Ayyub was the richest man who lost everything: wealth, children, and health. He was covered in worms but never complained. He was patient for 18 years. When he called to Allah, his health and wealth were restored.','practice',2,'["verbal"]','[""]','Ayyub patience story, never give up lesson'],
    ['is-see61',s,'seerah-enhanced',5,'5-6','Prophets Dawud and Sulayman','Dawud killed Goliath with a sling. Allah gave him the Zabur (Psalms). He could make iron soft with his hands. His son Sulayman understood animal language and had jinn working for him. Both were grateful kings. (Quran 2:251, 21:78-82, 27:15-44)','practice',2,'["verbal","visual"]','[""]','Dawud and Sulayman story cards, gratitude lesson'],
    ['is-see62',s,'seerah-enhanced',5,'5-6','Prophets Hud, Salih, and Shuaib','Hud called the people of Aad (giants who built on high places). Salih called Thamud (who carved homes in mountains) and the she-camel was a miracle. Shuaib called Madyan (cheaters in trade). Each nation was destroyed after rejecting.','practice',2,'["verbal","visual"]','[""]','prophets poster, destroyed nations lesson, honesty reminder'],

    // ═══════════════════════════════════════════════════════════
    // MIRACLES, NAMES & SHAMAIL
    // ═══════════════════════════════════════════════════════════
    ['is-see63',s,'seerah-enhanced',4,'4-5','The Miracles of the Prophet','The greatest miracle: the Quran. Other miracles: splitting the moon, water flowing between his fingers, food multiplying, the tree trunk crying, the pebbles glorifying Allah, the sick camel complaining to him. (Sahih al-Bukhari, Muslim)','practice',3,'["verbal","visual"]','[""]','miracles card set, moon-splitting story, Quran miracle lesson'],
    ['is-see64',s,'seerah-enhanced',4,'4-5','The Names and Titles of the Prophet','The Prophet has many beautiful names: Muhammad (praised one), Ahmad (most praised), Al-Amin (trustworthy), Al-Mustafa (chosen one), Al-Rasul (messenger), Al-Nabi (prophet), Al-Rahmah (mercy), Al-Shafii (intercessor), Al-Sadiq (truthful).','practice',2,'["verbal","visual"]','[""]','Prophet names poster, names meaning matching game'],
    ['is-see65',s,'seerah-enhanced',5,'5-6','The Seals of Prophethood','Between the Prophets shoulders was a seal, the size of a pigeon egg. It said: Muhammad Rasul Allah. This was one of the physical signs confirming he was Allahs messenger, known to people of previous scriptures.','practice',1,'["verbal","visual"]','[""]','seal of prophethood illustration, companions descriptions'],
    ['is-see66',s,'seerah-enhanced',4,'4-5','The Animals of the Prophet','The Prophet had a camel named Qaswa (who refused to move until the Prophet chose the mosque location). A donkey named Yafur. A mule named Duldul (gift from the ruler of Egypt). Cats, birds, and other animals are in his stories.','practice',2,'["verbal","visual"]','[""]','Prophet animals cards, kindness to animals lesson'],
    ['is-see67',s,'seerah-enhanced',4,'4-5','Makkah: The Blessed City','Makkah is the holiest city: home of the Kabah, the sacred mosque, Zamzam water, the birthplace of the Prophet, Cave Hira, Cave Thawr. Every Muslim faces it in prayer. The reward of salah there is multiplied 100,000 times.','practice',2,'["verbal","visual"]','[""]','Makkah landmarks poster, Kabah craft, Makkah map'],
    ['is-see68',s,'seerah-enhanced',4,'4-5','Madinah: The City of the Prophet','Madinah is the second holiest city: the Prophets mosque, his grave, Quba mosque (first mosque), Masjid al-Qiblatayn, the market of the Ansar, Uhud mountain (which loves us). Abu Hamid al-Ghazali said: Madinah is the light.','practice',2,'["verbal","visual"]','[""]','Madinah landmarks poster, Quba virtue, Uhud love cards'],
    ['is-see69',s,'seerah-enhanced',3,'3-4','The Pre-Islamic Arabia (Jahiliyyah)','Before Islam, Arabia was full of idol worship, burying baby girls alive, tribal wars, drinking, and injustice. The people had forgotten Ibrahim and Ismails teachings. The world waited for the final prophet. Allah sent Muhammad as a mercy.','practice',2,'["verbal","visual"]','[""]','Jahiliyyah vs Islam comparison cards, gratitude for Islam lesson'],

    // ═══════════════════════════════════════════════════════════
    // FAREWELL HAJJ & LEGACY DETAILED
    // ═══════════════════════════════════════════════════════════
    ['is-see70',s,'seerah-enhanced',6,'6-7','The Farewell Hajj in Detail','In 10 AH, the Prophet performed Hajj with 100,000+ companions. He taught every step. His sermon at Arafah covered: prohibition of usury, blood vengeance, rights of women, equality of all people, and clinging to Quran and Sunnah.','practice',3,'["verbal","visual"]','[""]','farewell sermon poster, Hajj step-by-step, equality lesson'],
    ['is-see71',s,'seerah-enhanced',6,'6-7','The Illness and Death of the Prophet','The Prophet fell ill for 13 days. Despite severe pain, he led salah until he could not. Abu Bakr led the salah. He passed away on Monday, 12 Rabi al-Awwal 11 AH, in Aishas room at age 63. His last words: Ar-Rafiq al-Ala (The Highest Companion).','practice',3,'["verbal"]','[""]','final days timeline, Aisha narration, legacy of Prophet'],
    ['is-see72',s,'seerah-enhanced',6,'6-7','The Legacy of the Prophet','The Prophet left us: the Quran, the Sunnah, his beautiful example (uswah hasanah), the Companions, and the Ummah. His light continues. Every Muslim who follows his way is part of his legacy. Quran 33:21.','mastery',3,'["verbal","visual"]','[""]','legacy tree craft, applying seerah in daily life, action cards'],
    ['is-see73',s,'seerah-enhanced',6,'6-7','The Seerah Timeline: Complete Overview','Complete timeline: 570 CE birth, 610 CE first revelation, 615 CE Abyssinia hijrah, 619 CE Year of Sorrow, 620 CE Isra wal-Miraj, 622 CE Hijrah, 624 CE Badr, 625 CE Uhud, 627 CE Khandaq, 628 CE Hudaybiyyah and Khaybar, 630 CE Conquest of Makkah and Hunayn and Tabuk, 632 CE Farewell Hajj and death.','mastery',4,'["visual","verbal"]','[""]','timeline poster, 60 events cards, chronological order game'],
  ];

  for (let i = 0; i < t.length; i += 5) {
    const batch = t.slice(i, i + 5);
    const values = batch.map(r =>
      `('${r[0]}','${r[1]}','${r[2]}',${r[3]},'${r[4]}','${r[5]}','${r[6]}','${r[7]}',${r[8]},'${r[9]}','${r[10]}','${r[11]}')`
    ).join(',');
    await prisma.$executeRawUnsafe(
      `INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES ${values}`
    );
    console.log(`  Seerah Batch ${Math.floor(i/5)+1}: topics ${i+1}-${Math.min(i+5,t.length)}`);
  }
  console.log(`  Seeded ${t.length} Seerah topics`);
}
