import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

/**
 * Islamic Curriculum Seed — Aqeedah, Fiqh, Seerah
 * Sunni (Salafi) appropriate, age-appropriate for levels 0-6
 * 3 subjects × 7 levels = 21 topic groups
 */
export async function seedIslamicCurriculum() {
  const existing = await prisma.$queryRawUnsafe<{cnt: number}[]>(
    "SELECT COUNT(*) as cnt FROM \"CurriculumTopic\" WHERE subject='aqeedah'"
  );
  if (Number(existing[0]?.cnt ?? 0) > 0) {
    console.log('  Islamic curriculum (aqeedah/fiqh/seerah) already exists — skipping.');
    return;
  }
  console.log("Seeding Islamic curriculum (aqeedah, fiqh, seerah)...");

  // =========================================================================
  // AQEEDAH — Levels 0-6
  // =========================================================================

  console.log("  Batch 1: aqeedah levels 0-1");
  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
    ('aq-001','aqeedah','aqeedah-foundations',0,'0-1','Allah Created Me','Learn that Allah is the One who created us — we did not create ourselves. Refer to Surah An-Naba 78:6-8: ''Did We not create you from a despised fluid?''','introduction',2,'["visual","verbal"]','[""]','soft picture book, nature sounds'),
    ('aq-002','aqeedah','aqeedah-foundations',0,'0-1','Allah Watches Over Me','Feel safe knowing Allah always sees and cares for us. Refer to Quran 4:1: ''Fear your Lord Who created you from one soul.''','introduction',2,'["visual","verbal"]','[""]','comforting images, bedtime routine'),
    ('aq-003','aqeedah','aqeedah-foundations',0,'0-1','Saying Alhamdulillah','Learn to say ''Alhamdulillah'' (All praise is due to Allah) after eating, drinking, or when happy. Refer to Quran 1:2.','introduction',2,'["verbal"]','[""]','snack time, parent modeling'),
    ('aq-004','aqeedah','aqeedah-foundations',1,'1-2','Allah Made the Sun and Moon','Recognize that the sun and moon are creations of Allah. Refer to Quran 21:33: ''It is not allowable for the sun to reach the moon.''','introduction',2,'["visual","verbal"]','["aq-001"]','sun and moon pictures, day/night activity'),
    ('aq-005','aqeedah','aqeedah-foundations',1,'1-2','Allah Made the Animals','Identify animals as Allah''s creation. Refer to Quran 42:29: ''Among His signs is the creation of the heavens and earth, and what He has dispersed in them of creatures.''','introduction',2,'["visual","verbal"]','["aq-001"]','animal flashcards, toy animals'),
    ('aq-006','aqeedah','aqeedah-foundations',1,'1-2','Allahu Akbar — Allah is the Greatest','Learn the phrase ''Allahu Akbar'' — Allah is greater than everything. Say it when we see amazing things.','introduction',2,'["verbal","visual"]','["aq-001"]','outdoor nature walks, voice recording'),
    ('aq-007','aqeedah','aqeedah-foundations',1,'1-2','Saying SubhanAllah','Learn to say ''SubhanAllah'' (Glory be to Allah) when we see beautiful creations. Refer to Quran 59:24.','introduction',2,'["verbal"]','["aq-004"]','nature walks, picture cards');`);
  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
    ('aq-008','aqeedah','aqeedah-foundations',2,'2-3','La Ilaha Illallah — There is No God But Allah','Learn the most important statement in Islam: There is nothing worthy of worship except Allah. Refer to Quran 3:62.','introduction',3,'["verbal","visual"]','["aq-006"]','flashcards, nasheed, repetition practice'),
    ('aq-009','aqeedah','aqeedah-names-allah',2,'2-3','Allah Hears Everything (As-Sami)','Learn that Allah hears every sound — our words, our duaa, even our whispers. Refer to Quran 2:127: ''Indeed, He is the All-Hearing, the All-Knowing.''','introduction',2,'["visual","verbal"]','["aq-001"]','listening game, ear picture card'),
    ('aq-010','aqeedah','aqeedah-names-allah',2,'2-3','Allah Sees Everything (Al-Baseer)','Learn that Allah sees everything — even when no one else can. Refer to Quran 58:7: ''Allah knows what every soul conceals.''','introduction',2,'["visual","verbal"]','["aq-002"]','eye picture card, peek-a-boo game'),
    ('aq-011','aqeedah','aqeedah-foundations',2,'2-3','Allah is the Creator of Everything','Everything in the sky, on earth, and in the sea was created by Allah. Refer to Quran 6:102: ''That is Allah, your Lord; there is no deity except Him, the Creator of all things.''','introduction',2,'["visual","hands-on"]','["aq-001"]','clay play (creating), nature walk'),
    ('aq-012','aqeedah','aqeedah-names-allah',2,'2-3','Allah is Ar-Rahman — The Most Merciful','Allah''s mercy encompasses everything. Refer to Quran 7:156: ''My mercy encompasses all things.''','introduction',2,'["visual","verbal"]','["aq-008"]','Mercy picture cards, hug activity'),
    ('aq-013','aqeedah','aqeedah-names-allah',2,'2-3','Allah is Al-Khaliq — The Creator','Allah creates everything from nothing. First simple Names of Allah lesson. Refer to Quran 59:24.','introduction',2,'["verbal","visual"]','["aq-011"]','creation collage, picture cards'),
    ('aq-014','aqeedah','aqeedah-prophets',2,'2-3','Prophet Muhammad ﷺ is Allah''s Messenger','Prophet Muhammad ﷺ was sent by Allah to teach us Islam. He is the last and final prophet. Refer to Quran 33:40.','introduction',2,'["verbal","visual"]','["aq-008"]','simple seerah picture book, nasheed');`);
  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
    ('aq-015','aqeedah','aqeedah-iman-articles',3,'3-4','Believing in Allah (Iman bil Allah)','First pillar of Iman — believe in Allah, His Angels, His Books, His Messengers, the Last Day, and Qadr. This lesson focuses on Allah. Refer to Quran 2:177.','introduction',2,'["verbal","visual"]','["aq-008"]','iman poster, coloring worksheet'),
    ('aq-016','aqeedah','aqeedah-iman-articles',3,'3-4','Believing in the Angels (Iman bil Mala''ikah)','Angels are made of light, they always obey Allah, and they do not eat or sleep. Jibril brought the Quran. Refer to Quran 66:6: ''Angels have wings, two, three, or four.''','introduction',2,'["visual","verbal"]','["aq-015"]','angel picture cards, craft project'),
    ('aq-017','aqeedah','aqeedah-iman-articles',3,'3-4','Believing in the Books (Iman bil Kutub)','Allah sent Books to guide people: Taurat to Musa, Zabur to Dawud, Injeel to Isa, Quran to Muhammad ﷺ. Refer to Quran 2:4.','introduction',2,'["visual","verbal"]','["aq-015"]','book-shaped cards, simple timeline'),
    ('aq-018','aqeedah','aqeedah-iman-articles',3,'3-4','Believing in the Prophets (Iman bil Rusul)','Allah sent prophets to every nation to guide them. Muhammad ﷺ is the last. Refer to Quran 33:40.','introduction',2,'["verbal","visual"]','["aq-015"]','prophet name flashcards'),
    ('aq-019','aqeedah','aqeedah-iman-articles',3,'3-4','Believing in the Last Day (Iman bil Yawm al-Akhir)','There will be a Day of Judgment when everyone will meet Allah. Refer to Quran 99:7-8.','introduction',2,'["verbal","visual"]','["aq-015"]','simple story cards, coloring'),
    ('aq-020','aqeedah','aqeedah-iman-articles',3,'3-4','Believing in Qadr — Allah''s Decree','Everything happens by Allah''s will and knowledge — both good and bad. Refer to Quran 57:22: ''No calamity occurs except by permission of Allah.''','introduction',2,'["verbal"]','["aq-015"]','storytelling, discussion circles'),
    ('aq-021','aqeedah','aqeedah-names-allah',3,'3-4','Allah is Ar-Razzaq — The Provider','Allah provides food, drink, and everything we need. Refer to Quran 51:58: ''Indeed, Allah is the Provider, the Possessor of Strength.''','introduction',2,'["verbal","hands-on"]','["aq-012"]','mealtime dua, provider activity'),
    ('aq-022','aqeedah','aqeedah-foundations',3,'3-4','Allah Loves Good Deeds','When we are kind, honest, and obey Allah, He loves us. Refer to Quran 3:134: ''Allah loves the doers of good.''','introduction',2,'["verbal","visual"]','["aq-015"]','deed chart, sticker reward system');`);
  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
    ('aq-023','aqeedah','aqeedah-iman-articles',4,'4-5','The Five Pillars of Islam — Overview','Shahada, Salah, Zakat, Sawm, Hajj — the five actions every Muslim must know and do. Refer to Hadith of Jibril (Sahih Muslim).','introduction',3,'["visual","verbal"]','["aq-015"]','five pillars poster, hand chart (5 fingers = 5 pillars)'),
    ('aq-024','aqeedah','aqeedah-iman-articles',4,'4-5','Jibril (Gabriel) — Angel of Revelation','Jibril is the greatest angel. He brought Allah''s messages to the prophets. He brought the Quran to Muhammad ﷺ. Refer to Quran 2:97.','introduction',2,'["visual","verbal"]','["aq-016"]','angel storybook, revelation timeline'),
    ('aq-025','aqeedah','aqeedah-iman-articles',4,'4-5','Mikail (Michael) — Angel of Provision','Mikail is responsible for rain, plants, and sustenance. He works day and night providing for Allah''s creation.','introduction',2,'["visual","verbal"]','["aq-016"]','rain experiment, food discussion'),
    ('aq-026','aqeedah','aqeedah-iman-articles',4,'4-5','Israfil and Azrael — Angels of the Trumpet and Death','Israfil will blow the trumpet on the Day of Judgment. Azrael (Malak al-Mawt) takes the soul at the time of death. Refer to Quran 6:73.','introduction',2,'["verbal","visual"]','["aq-016"]','simple picture cards, respectful discussion'),
    ('aq-027','aqeedah','aqeedah-iman-articles',4,'4-5','The Quran — Allah''s Final Book','The Quran is the last and most complete revelation, preserved perfectly. It was revealed over 23 years. Refer to Quran 15:9: ''Indeed, it is We who sent down the Quran.''','introduction',2,'["verbal","visual"]','["aq-017"]','Quran mushaf, revelation timeline'),
    ('aq-028','aqeedah','aqeedah-iman-articles',4,'4-5','Previous Books — Taurat, Zabur, Injeel','The Taurat was sent to Musa (AS), Zabur to Dawud (AS), and Injeel to Isa (AS). The Quran confirms and corrects them. Refer to Quran 3:3-4.','introduction',2,'["verbal","visual"]','["aq-017"]','book comparison chart, prophet cards'),
    ('aq-029','aqeedah','aqeedah-names-allah',4,'4-5','Names of Allah: Ar-Rahman and Ar-Raheem','Ar-Rahman = The Most Gracious to all creation. Ar-Raheem = The especially Merciful to the believers. Refer to Quran 1:1-2.','introduction',2,'["verbal","visual"]','["aq-012"]','names poster, calligraphy practice'),
    ('aq-030','aqeedah','aqeedah-names-allah',4,'4-5','Names of Allah: Al-Malik and Al-Quddus','Al-Malik = The King and Sovereign of all. Al-Quddus = The Holy, Pure, free from any flaw. Refer to Quran 59:23.','introduction',2,'["verbal","visual"]','["aq-012"]','crown craft (Al-Malik), names chart'),
    ('aq-031','aqeedah','aqeedah-foundations',4,'4-5','Allah Never Sleeps — Allah is Always Watchful','Unlike us, Allah never sleeps or rests. He is always aware of everything. Refer to Quran 2:255 (Ayat al-Kursi).','introduction',2,'["verbal","visual"]','["aq-010"]','Ayat al-Kursi poster, bedtime dua'),
    ('aq-032','aqeedah','aqeedah-foundations',4,'4-5','Allah is Not Like His Creation','Allah is unique — nothing is like Him. He has no parents, no children, no partners. Refer to Quran 112:1-4: ''Say: He is Allah, the One.''','introduction',2,'["verbal","visual"]','["aq-008"]','Surah Al-Ikhlas coloring, discussion');`);
  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
    ('aq-033','aqeedah','aqeedah-iman-articles',5,'5-6','The Six Articles of Iman — Detailed','Expand on each article: Allah, Angels, Books, Messengers, Last Day, Qadr. Each explained with proofs from Quran and Sunnah.','practice',4,'["verbal","visual"]','["aq-015"]','iman booklet project, quiz cards'),
    ('aq-034','aqeedah','aqeedah-names-allah',5,'5-6','Names of Allah: Al-Alim, Al-Qadir, As-Sami, Al-Baseer','Al-Alim = The All-Knowing. Al-Qadir = The All-Powerful. As-Sami = The All-Hearing. Al-Baseer = The All-Seeing.','practice',3,'["verbal","visual"]','["aq-009","aq-010"]','names worksheet, matching game'),
    ('aq-035','aqeedah','aqeedah-names-allah',5,'5-6','Names of Allah: Al-Hakim, Al-Halim, Al-Wadud, Al-Ghaffar','Al-Hakim = The Wise. Al-Halim = The Forbearing. Al-Wadud = The Loving. Al-Ghaffar = The Forgiving.','practice',3,'["verbal","visual"]','["aq-034"]','calligraphy cards, daily name practice'),
    ('aq-036','aqeedah','aqeedah-names-allah',5,'5-6','Names of Allah: Al-Mumin, Al-Muhaymin, Al-Jabbar, Al-Mutakabbir','Al-Mumin = The Giver of Security. Al-Muhaymin = The Guardian. Al-Jabbar = The Compeller. Al-Mutakabbir = The Supreme.','practice',3,'["verbal","visual"]','["aq-034"]','discussion cards, journaling'),
    ('aq-037','aqeedah','aqeedah-names-allah',5,'5-6','Names of Allah: Ar-Razzaq, Al-Fattah, Al-Alim, Ad-Darr, An-Nafi','Ar-Razzaq = The Provider. Al-Fattah = The Opener. Ad-Darr = The Harmer. An-Nafi = The Benefiter.','practice',3,'["verbal","visual"]','["aq-034"]','daily dua worksheet, names journal'),
    ('aq-038','aqeedah','aqeedah-prophets',5,'5-6','The 25 Prophets Named in the Quran','Learn their names in order: Adam, Idris, Nuh, Hud, Salih, Ibrahim, Lut, Ismail, Ishaq, Yaqub, Yusuf, Ayyub, Shu''ayb, Musa, Harun, Dhul-Kifl, Dawud, Sulaiman, Ilyas, Al-Yasa, Yunus, Zakariya, Yahya, Isa, Muhammad ﷺ.','practice',4,'["verbal","visual"]','["aq-018"]','prophet timeline poster, name cards'),
    ('aq-039','aqeedah','aqeedah-prophets',5,'5-6','Prophet Adam (AS) — First Human and Prophet','Allah created Adam from clay, taught him all names, and commanded the angels to prostrate. Iblis refused out of pride. Refer to Quran 2:30-37.','practice',2,'["verbal","visual"]','["aq-038"]','clay activity, storybook'),
    ('aq-040','aqeedah','aqeedah-prophets',5,'5-6','Prophet Nuh (AS) — The Patient Caller','Nuh called his people for 950 years. He built the ark by Allah''s command. The flood saved the believers. Refer to Quran 11:25-49.','practice',2,'["verbal","visual"]','["aq-038"]','ark craft, flood story cards'),
    ('aq-041','aqeedah','aqeedah-prophets',5,'5-6','Prophet Ibrahim (AS) — The Friend of Allah','Ibrahim searched for truth, destroyed idols, was thrown in fire that became cool, and built the Ka''bah. Refer to Quran 21:51-73.','practice',2,'["verbal","visual"]','["aq-038"]','fire experiment (safe), Ka''bah model'),
    ('aq-042','aqeedah','aqeedah-prophets',5,'5-6','Prophet Musa (AS) — Talker with Allah','Musa spoke directly with Allah at Tur (Sinai). He led Bani Israil out of Egypt. Refer to Quran 28:14-30.','practice',2,'["verbal","visual"]','["aq-038"]','sea parting experiment, storybook'),
    ('aq-043','aqeedah','aqeedah-prophets',5,'5-6','Prophet Isa (AS) — Word of Allah and Spirit','Isa was born to Maryam without a father. He was a prophet, not divine. He will return before the Day of Judgment. Refer to Quran 3:45-47.','practice',2,'["verbal","visual"]','["aq-038"]','story cards, discussion'),
    ('aq-044','aqeedah','aqeedah-foundations',5,'5-6','The Quran is the Word of Allah — Not Created','The Quran is Allah''s speech, revealed to Muhammad ﷺ through Jibril. It has been perfectly preserved since its revelation. Refer to Quran 15:9.','practice',2,'["verbal","visual"]','["aq-027"]','mushaf handling practice, history timeline');`);
  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
    ('aq-045','aqeedah','aqeedah-tawhid',6,'6-7','Rububiyyah — Lordship of Allah Alone','Allah alone is the Creator, Provider, and Controller of all affairs. No one shares in His Lordship. Refer to Quran 6:102, 39:62.','practice',3,'["verbal","visual"]','["aq-044"]','tawhid tree diagram, evidence booklet'),
    ('aq-046','aqeedah','aqeedah-tawhid',6,'6-7','Uluhiyyah — Worship Allah Alone','All acts of worship — dua, sacrifice, hope, fear — must be directed to Allah alone. Refer to Quran 51:56: ''I did not create jinn and mankind except to worship Me.''','practice',3,'["verbal"]','["aq-045"]','worship checklist, discussion'),
    ('aq-047','aqeedah','aqeedah-tawhid',6,'6-7','Asma wa Sifat — Names and Attributes of Allah','Allah has perfect names and attributes that befit His Majesty. We affirm them without denying, distorting, or comparing them to creation. Refer to Quran 17:110.','practice',3,'["verbal","visual"]','["aq-036"]','99 Names poster, weekly name study'),
    ('aq-048','aqeedah','aqeedah-tawhid',6,'6-7','The 99 Names of Allah — Study and Memorization','Begin memorizing and understanding the 99 Names. Use them in dua and daily life. Refer to hadith: ''Allah has 99 Names, 100 minus one.'' (Sahih al-Bukhari 2736).','practice',4,'["verbal","visual"]','["aq-047"]','names booklet, flashcards, dua journal'),
    ('aq-049','aqeedah','aqeedah-tawhid',6,'6-7','Shirk — The Greatest Sin','Shirk means associating partners with Allah. It is the only sin that will never be forgiven if one dies without repenting. Refer to Quran 4:48, 4:116.','practice',2,'["verbal","visual"]','["aq-045","aq-046"]','comparison chart (Tawhid vs Shirk), examples'),
    ('aq-050','aqeedah','aqeedah-tawhid',6,'6-7','Types of Shirk — Major and Minor','Major Shirk: worshipping others besides Allah. Minor Shirk: showing off (riya), using amulets, etc. Refer to hadith about riya in Sahih al-Bukhari 32.','practice',3,'["verbal"]','["aq-049"]','scenario cards, self-reflection journal'),
    ('aq-051','aqeedah','aqeedah-tawhid',6,'6-7','Tawbah — Repentance to Allah','Tawbah means turning back to Allah with regret, stopping the sin, resolving not to return, and making up for any rights of others. Refer to Quran 3:135, 66:8.','practice',2,'["verbal"]','["aq-049"]','tawbah steps poster, reflection journal'),
    ('aq-052','aqeedah','aqeedah-tawhid',6,'6-7','Mu''amalah Basics — Dealing with People Fairly','Islamic transactions: honesty, no cheating, no interest (riba), fulfilling contracts. Refer to Quran 2:275 (prohibition of riba), hadith about trade practices.','practice',2,'["verbal","hands-on"]','["aq-046"]','role-play activities, transaction scenarios'),
    ('aq-053','aqeedah','aqeedah-tawhid',6,'6-7','Ihsan — Worshiping Allah as if You See Him','The highest level of faith: worship Allah with excellence, as if you see Him, knowing that even if you cannot see Him, He sees you. Hadith of Jibril (Sahih Muslim 8).','practice',2,'["verbal"]','["aq-046","aq-047"]','discussion circles, ihsan tracker'),
    ('aq-054','aqeedah','aqeedah-tawhid',6,'6-7','The Shahada — Mean What You Say','The Shahada is not just words — it requires knowledge, acceptance, certainty, submission, and sincerity. Refer to Quran 63:1-3.','practice',2,'["verbal"]','["aq-046"]','shahada booklet, commitment discussion'),
    ('aq-055','aqeedah','aqeedah-tawhid',6,'6-7','The Kalima at-Tayyibah and Kalima ash-Shahadatayn','La ilaha illallah Muhammadur Rasulullah — explained in depth. What it means to testify and how it changes our lives.','practice',2,'["verbal"]','["aq-054"]','calligraphy practice, memorization cards'),
    ('aq-056','aqeedah','aqeedah-tawhid',6,'6-7','Famous Companions and Their Iman — Abu Bakr (RA)','Abu Bakr As-Siddiq was the first man to accept Islam. He was always truthful and steadfast. He spent his wealth for Allah''s cause. Refer to Quran 9:40.','practice',2,'["verbal","visual"]','["aq-054"]','companion profile cards, biography reading'),
    ('aq-057','aqeedah','aqeedah-tawhid',6,'6-7','Famous Companions — Umar (RA), Uthman (RA), Ali (RA)','Brief profiles: Umar''s justice, Uthman''s generosity (bought the well of Rumah, equipped the army of Usrah), Ali''s knowledge and courage.','practice',2,'["verbal","visual"]','["aq-056"]','companion cards, group discussion'),
    ('aq-058','aqeedah','aqeedah-tawhid',6,'6-7','The Importance of Tawhid in Our Lives','Tawhid is the foundation of everything in a Muslim''s life — our worship, our character, our worldview. It gives us purpose and peace.','mastery',2,'["verbal"]','["aq-050","aq-053"]','personal reflection essay, tawhid pledge');`);

  // =========================================================================
  // FIQH — Levels 0-6
  // =========================================================================

  console.log("  Batch 2: fiqh levels 0-1");
  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
    ('fq-001','fiqh','fiqh-food',0,'0-1','Clean Hands Before Eating','Teach the child that we wash our hands before eating. Allah loves cleanliness. Refer to hadith: ''Cleanliness is half of faith.'' (Sahih Muslim 223).','introduction',2,'["hands-on","visual"]','[""]','soap, water, hand-washing song'),
    ('fq-002','fiqh','fiqh-food',0,'0-1','Saying Bismillah Before Eating','Model saying ''Bismillah'' (In the name of Allah) before giving food to the child. Every act begins with Allah''s name.','introduction',2,'["verbal"]','[""]','mealtime routine, parent modeling'),
    ('fq-003','fiqh','fiqh-adab',0,'0-1','Basic Hygiene — Wiping Face and Hands','After eating, wipe the face and hands. Simple cleanliness habits from the earliest age.','introduction',2,'["hands-on"]','[""]','baby wipes, washcloth');`);
  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
    ('fq-004','fiqh','fiqh-purity',1,'1-2','Washing Hands with Water','More detailed hand-washing: water, rub, rinse. Teach the concept that water cleans us. Refer to hadith about water purification.','practice',2,'["hands-on","verbal"]','["fq-001"]','sink, soap, timer (20 seconds)'),
    ('fq-005','fiqh','fiqh-food',1,'1-2','Saying Alhamdulillah After Eating','Say ''Alhamdulillah'' (All praise is due to Allah) after finishing food and drink. Refer to Quran 1:2.','practice',2,'["verbal"]','["fq-002"]','mealtime routine'),
    ('fq-006','fiqh','fiqh-adab',1,'1-2','Saying Assalamu Alaikum — Islamic Greeting','Greet people with ''Assalamu Alaikum wa Rahmatullah'' (Peace and mercy of Allah be upon you). Refer to hadith: ''Spread salam among yourselves.'' (Sahih Muslim 54).','introduction',2,'["verbal"]','[""]','greeting role play, greeting cards'),
    ('fq-007','fiqh','fiqh-adab',1,'1-2','Eating with the Right Hand','The Prophet ﷺ ate with his right hand. Refer to hadith: ''When one of you eats, let him eat with his right hand.'' (Sahih Muslim 2020a).','practice',2,'["verbal","hands-on"]','["fq-002"]','mealtime practice, right/left identification');`);
  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
    ('fq-008','fiqh','fiqh-purity',2,'2-3','Wudu — Washing the Face','First step of wudu: wash the face from forehead to chin, ear to ear. Refer to Quran 5:6: ''...wash your faces.''','practice',2,'["hands-on","visual"]','["fq-004"]','wudu mat, basin, step-by-step poster'),
    ('fq-009','fiqh','fiqh-purity',2,'2-3','Wudu — Washing the Arms','Wash both arms from fingertips to elbows, right then left. Refer to Quran 5:6: ''...and your arms up to the elbows.''','practice',2,'["hands-on","visual"]','["fq-008"]','wudu poster, practice at sink'),
    ('fq-010','fiqh','fiqh-purity',2,'2-3','Wudu — Wiping the Head and Ears','Wipe the head from front to back and back to front. Clean the ears with water. Refer to Sunnah of wudu in Sahih al-Bukhari 159.','practice',2,'["hands-on","visual"]','["fq-008"]','wudu poster, ear cleaning demo'),
    ('fq-011','fiqh','fiqh-purity',2,'2-3','Wudu — Washing the Feet','Wash both feet including the ankles, right then left. Refer to Quran 5:6: ''...and your feet up to the ankles.''','practice',2,'["hands-on","visual"]','["fq-008"]','wudu station, foot washing practice'),
    ('fq-012','fiqh','fiqh-salah',2,'2-3','Clean Clothes for Salah','Before praying, wear clean clothes. Salah requires cleanliness. Refer to hadith: ''Allah does not accept prayer from an impure person.'' (Sahih Muslim 225).','introduction',2,"["visual","verbal"]","["fq-008"]","clean clothes, dirty clothes comparison cards"),
    ('fq-013','fiqh','fiqh-salah',2,'2-3','Standing in Prayer (Qiyam)','Stand facing the Qiblah (direction of Ka''bah), hands folded on chest. Stand still and focused. Refer to Sahih al-Bukhari 723.','introduction',2,'["visual","hands-on"]','["fq-012"]','qiblah compass, prayer position poster'),
    ('fq-014','fiqh','fiqh-salah',2,'2-3','Saying Assalamu Alaikum to End Prayer','Turn head right then left saying ''Assalamu Alaikum wa Rahmatullah''. This ends the salah. Refer to Sahih Muslim 498.','practice',2,'["verbal","hands-on"]','["fq-013"]','prayer sequence cards, model prayer');`);
  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
    ('fq-015','fiqh','fiqh-salah',3,'3-4','Ruku — Bowing in Prayer','Bend at the waist, hands on knees, back straight. Say ''Subhana Rabbiyal Adheem'' (Glory be to my Lord, the Most Great). Refer to Sahih al-Bukhari 738.','practice',2,'["hands-on","verbal"]','["fq-013"]','rukua position demo, tasbih cards'),
    ('fq-016','fiqh','fiqh-salah',3,'3-4','Sujud — Prostration in Prayer','Place forehead, nose, palms, knees, and toes on the ground. Say ''Subhana Rabbiyal A''la'' (Glory be to my Lord, the Most High). Refer to Sahih al-Bukhari 790.','practice',2,'["hands-on","verbal"]','["fq-015"]','prostration position demo, sujud tasbih cards'),
    ('fq-017','fiqh','fiqh-salah',3,'3-4','Between Two Prostrations (Jalsa)','Sit upright between the two prostrations. Say ''Rabbighfir li warhamni'' (My Lord, forgive me and have mercy on me). Refer to Sahih Muslim 399.','practice',2,'["hands-on","verbal"]','["fq-016"]','prayer sequence cards, sitting position demo'),
    ('fq-018','fiqh','fiqh-salah',3,'3-4','Takbirat al-Ihram — Starting Prayer','Say ''Allahu Akbar'' to begin the prayer with sincere intention (niyyah). This marks entering the prayer. Refer to Sahih al-Bukhari 1.','practice',2,'["verbal","hands-on"]','["fq-013"]','takbir practice, intention reminder card'),
    ('fq-019','fiqh','fiqh-food',3,'3-4','Halal Food — What Allah Permits','Only eat what Allah has allowed: meat from properly slaughtered animals, vegetables, fruits. Avoid pork and blood. Refer to Quran 2:168, 5:3.','practice',2,'["visual","verbal"]','["fq-005"]','halal food chart, food sorting game'),
    ('fq-020','fiqh','fiqh-adab',3,'3-4','Islamic Greetings — Assalamu Alaikum and More','Greetings in Islam: Assalamu Alaikum, JazakAllahu Khairan, MashAllah, SubhanAllah, Alhamdulillah, InshaAllah.','practice',2,'["verbal"]','["fq-006"]','greeting cards, role play scenarios'),
    ('fq-021','fiqh','fiqh-food',3,'3-4','Saying Bismillah with Full Basmalah','Say ''Bismillahir Rahmanir Rahim'' (In the name of Allah, the Most Gracious, the Most Merciful) before eating. Refer to hadith: ''Mention Allah''s name, eat with your right hand.'' (Sahih Muslim 2019).','practice',2,'["verbal","hands-on"]','["fq-002"]','basmalah tracing worksheet, mealtime practice'),
    ('fq-022','fiqh','fiqh-food',3,'3-4','Do Not Waste Food — Do Not Be Wasteful','Allah does not love those who waste. Eat what you take. Refer to Quran 6:141: ''...and do not waste, for He does not like the wasteful.''','practice',2,'["verbal","visual"]','["fq-019"]','portion sizing activity, waste discussion');`);
  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
    ('fq-023','fiqh','fiqh-salah',4,'4-5','The Five Daily Prayers — Names and Times','Fajr (dawn), Dhuhr (noon), Asr (afternoon), Maghrib (sunset), Isha (night). Each prayer has a specific time window. Refer to Quran 11:114, 17:78, 20:130.','introduction',3,'["visual","verbal"]','["fq-018"]','prayer time clock, daily schedule poster'),
    ('fq-024','fiqh','fiqh-salah',4,'4-5','Fajr Prayer — The Morning Prayer','Two rak''ahs before sunrise. The Prophet ﷺ said: ''Whoever prays Fajr is under Allah''s protection.'' (Sahih Muslim 657).','practice',2,'["verbal","hands-on"]','["fq-023"]','early morning routine chart, dua cards'),
    ('fq-025','fiqh','fiqh-salah',4,'4-5','Dhuhr Prayer — The Noon Prayer','Four rak''ahs after the sun passes its zenith. The Prophet ﷺ said: ''The best prayer after Fajr is Asr, then Dhuhr.''','practice',2,'["verbal","hands-on"]','["fq-023"]','prayer tracking card, noon reminder'),
    ('fq-026','fiqh','fiqh-salah',4,'4-5','Asr Prayer — The Afternoon Prayer','Four rak''ahs in the late afternoon. The Prophet ﷺ warned: ''Whoever misses Asr, it is as if he lost his family and wealth.'' (Sahih al-Bukhari 593).','practice',2,'["verbal","hands-on"]','["fq-023"]','afternoon prayer routine, clock reading'),
    ('fq-027','fiqh','fiqh-salah',4,'4-5','Maghrib Prayer — The Sunset Prayer','Three rak''ahs after sunset. Refer to Quran 11:114: ''...establish prayer at the two ends of the day.''','practice',2,'["verbal","hands-on"]','["fq-023"]','sunset watching, prayer time chart'),
    ('fq-028','fiqh','fiqh-salah',4,'4-5','Isha Prayer — The Night Prayer','Four rak''ahs after the twilight disappears. The last prayer of the day. Refer to Quran 24:58.','practice',2,'["verbal","hands-on"]','["fq-023"]','nighttime routine chart, bedtime prayer'),
    ('fq-029','fiqh','fiqh-zakat',4,'4-5','Zakat — Giving to Those in Need','Zakat means giving 2.5% of your savings (that have been saved for one year) to poor Muslims. It purifies wealth. Refer to Quran 9:60.','introduction',2,'["verbal","visual"]','["fq-023"]','coin counting, charity jar'),
    ('fq-030','fiqh','fiqh-fasting',4,'4-5','Ramadan Fasting Basics','During Ramadan, we do not eat, drink, or argue from dawn (Fajr) to sunset (Maghrib). It teaches patience and taqwa. Refer to Quran 2:183.','introduction',2,'["verbal","visual"]','["fq-023"]','Ramadan calendar, iftar planner'),
    ('fq-031','fiqh','fiqh-salah',4,'4-5','Eid Prayers — Eid al-Fitr and Eid al-Adha','Two special prayers on Eid days, followed by takbir, khutbah, and celebration. Eid al-Fitr ends Ramadan. Eid al-Adha is during Hajj.','introduction',2,'["verbal","hands-on"]','["fq-030"]','Eid preparation checklist, takbir cards'),
    ('fq-032','fiqh','fiqh-salah',4,'4-5','Praying in Congregation — Following the Imam','Muslims pray together behind one Imam. Men pray in the mosque, women at home. Congregation is better. Refer to hadith: ''Prayer in congregation is 27 times better.'' (Sahih al-Bukhari 645).','practice',2,'["verbal","hands-on"]','["fq-023"]','congregation layout, imam/follower role play');`);
  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
    ('fq-033','fiqh','fiqh-purity',5,'5-6','Complete Wudu — All Steps in Order','Full wudu: Bismillah, wash hands 3x, mouth 3x, nose 3x, face 3x, arms 3x (right then left), wipe head once, ears once, feet 3x (right then left). Refer to Quran 5:6, Sahih al-Bukhari 159.','practice',3,'["hands-on","verbal"]','["fq-008","fq-009","fq-010","fq-011"]','wudu station, step-by-step poster, video'),
    ('fq-034','fiqh','fiqh-purity',5,'5-6','Sunnahs of Wudu — Prophetic Mannerisms','Run water between fingers and toes, rinse mouth vigorously, sniff water into nose, wipe each part 3 times, say the dua after wudu. Refer to Sahih al-Bukhari 159-166.','practice',2,'["hands-on","verbal"]','["fq-033"]','wudu checklist, hadith cards'),
    ('fq-035','fiqh','fiqh-purity',5,'5-6','Ghusl — Full Body Purification','Ghusl is required after certain states (janabah, menstruation, etc.). Wash the entire body with water. Refer to Sahih al-Bukhari 229, Sahih Muslim 316.','practice',2,'["verbal","visual"]','["fq-033"]','ghusl steps poster, respectful discussion'),
    ('fq-036','fiqh','fiqh-fasting',5,'5-6','Suhur — The Pre-Dawn Meal','Eat before Fajr during Ramadan. The Prophet ﷺ said: ''Take suhur, for in suhur there is blessing.'' (Sahih al-Bukhari 1923).','practice',2,'["verbal","hands-on"]','["fq-030"]','suhoor planner, early wake-up routine'),
    ('fq-037','fiqh','fiqh-fasting',5,'5-6','Iftar — Breaking the Fast at Sunset','Break the fast at Maghrib with dates and water, following the Sunnah of the Prophet ﷺ. Make dua before eating. Refer to Sahih al-Bukhari 1956.','practice',2,'["verbal","hands-on"]','["fq-030"]','iftar preparation, dua cards'),
    ('fq-038','fiqh','fiqh-fasting',5,'5-6','What Invalidates the Fast — Things That Break the Fast','Eating, drinking, or intentional vomiting breaks the fast. Intentional relations break the fast and require makeup and kaffarah. Refer to Sahih al-Bukhari 1933.','practice',2,'["verbal","visual"]','["fq-036"]','fasting rules chart, Q&A cards'),
    ('fq-039','fiqh','fiqh-zakat',5,'5-6','Zakat Details — Nisab and Calculation','Nisab is the minimum amount of wealth on which zakat is due (equivalent to 85g gold or 595g silver). Rate is 2.5%. Refer to hadith in Sahih Muslim 976.','practice',3,'["verbal","hands-on"]','["fq-029"]','calculation worksheets, gold/silver reference'),
    ('fq-040','fiqh','fiqh-zakat',5,'5-6','Zakat al-Fitr — Charity Before Eid','Every Muslim must give Zakat al-Fitr before Eid prayer. It is about 1.5-2kg of staple food per person. Refer to hadith in Sahih al-Bukhari 1511.','practice',2,'["verbal","hands-on"]','["fq-039"]','food bag preparation, Eid planning'),
    ('fq-041','fiqh','fiqh-hajj',5,'5-6','Hajj Overview — Pilgrimage to Makkah','Every Muslim who is able must perform Hajj once in a lifetime. It happens in the month of Dhul Hijjah. Refer to Quran 3:97.','introduction',2,'["visual","verbal"]','["fq-030"]','Makkah map, Hajj steps poster'),
    ('fq-042','fiqh','fiqh-hajj',5,'5-6','Ihram — Entering the Sacred State','Before Hajj, make the intention and enter Ihram: men wear white unstitched garments, women wear modest clothes. No cutting hair or nails. Refer to Quran 2:196.','practice',2,'["visual","verbal"]','["fq-041"]','ihram demonstration, Makkah pictures'),
    ('fq-043','fiqh','fiqh-hajj',5,'5-6','Tawaf — Circling the Ka''bah Seven Times','Walk around the Ka''bah seven times, starting and ending at the Black Stone. Make dua throughout. Refer to Quran 2:125, 22:26.','practice',2,'["verbal","hands-on"]','["fq-041"]","Ka'bah model, circular path activity"),
    ('fq-044','fiqh','fiqh-hajj',5,'5-6','Sa''i — Walking Between Safa and Marwa','Walk seven times between the hills of Safa and Marwa, remembering Hajar''s search for water. Refer to Quran 2:158.','practice',2,'["verbal","hands-on"]','["fq-041"]','walking activity, Hajar story cards');`);
  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
    ('fq-045','fiqh','fiqh-salah',6,'6-7','Conditions of Salah (Shurut) — What Must Be Present','13 conditions: Islam, cleanliness, removing najasah, covering aurah, facing Qiblah, prayer time, intention, saying Allahu Akbar, reciting Al-Fatihah, standing, ruku, sujud, order. Refer to Sahih al-Bukhari 757.','practice',3,'["verbal","visual"]','["fq-033"]','conditions checklist, conditions poster'),
    ('fq-046','fiqh','fiqh-salah',6,'6-7','Pillars of Salah (Arkan) — What Must Be Done','14 pillars: standing (for those able), saying Allahu Akbar, reciting Al-Fatihah, ruku, rising from ruku, sujud (twice), sitting between prostrations, sitting at-tashahhud, saying At-Tahiyyat, sending blessings on the Prophet ﷺ, saying Taslim, being at ease in each position, correct order, khushu. Refer to Sahih al-Bukhari 553.','practice',3,'["verbal","hands-on"]','["fq-045"]','pillars booklet, pillar vs sunnah comparison chart'),
    ('fq-047','fiqh','fiqh-salah',6,'6-7','Sunnahs of Salah — Prophetic Practices','Actions the Prophet ﷺ consistently did: raising hands for takbir, placing right hand on left below navel, saying Rabbana lakal hamd, saying Ameen silently, wiping ears in wudu, etc. Refer to Sahih al-Bukhari 738-830.','practice',3,'["verbal","hands-on"]','["fq-046"]','sunnahs checklist, hadith reference cards'),
    ('fq-048','fiqh','fiqh-salah',6,'6-7','What Invalidates Salah — Actions That Break Prayer','Talking, eating, drinking, turning away from Qiblah, laughing, making signs, covering face, and doing actions not part of prayer. Refer to Sahih al-Bukhari 121.','practice',2,'["verbal","visual"]','["fq-045"]','scenario cards, true/false quiz'),
    ('fq-049','fiqh','fiqh-salah',6,'6-7','Praying Sunnah Prayers — Rawatib Before and After','12 rak''ahs of sunnah prayers daily: 4 before Dhuhr, 2 after, 2 after Maghrib, 2 after Isha, 2 before Fajr. Refer to Sahih Muslim 728.','practice',2,'["verbal"]','["fq-046"]','prayer schedule chart, tracking sheet'),
    ('fq-050','fiqh','fiqh-salah',6,'6-7','Making Dua in Sujud — The Closest Position to Allah','The Prophet ﷺ said: ''The closest a servant is to his Lord is when he is in prostration, so increase your dua.'' (Sahih Muslim 482).','practice',2,'["verbal"]','["fq-046"]','sujud dua cards, dua journal'),
    ('fq-051','fiqh','fiqh-purity',6,'6-7','Tayammum — Dry Ablution','When water is unavailable or using it would cause harm, perform tayammum: strike clean earth, wipe face and arms. Refer to Quran 4:43, 5:6, Sahih al-Bukhari 347.','practice',2,'["hands-on","verbal"]','["fq-033"]','clean earth/sand, tayammum practice'),
    ('fq-052','fiqh','fiqh-funeral',6,'6-7','Funeral Prayer (Salat al-Janazah)','Four takbirs without ruku or sujud. After each: first takbir — Al-Fatihah, second — blessings on Prophet ﷺ, third — dua for the deceased, fourth — taslim. Refer to Sahih al-Bukhari 1254.','practice',2,'["verbal","visual"]','["fq-046"]','janazah prayer steps poster, respectful discussion'),
    ('fq-053','fiqh','fiqh-marriage',6,'6-7','Marriage Basics — Nikah in Islam','Marriage is a sunnah of the Prophet ﷺ. It requires: consent of both parties, a mahr (gift to bride), and a guardian (wali). Refer to hadith: ''Marriage is my sunnah.'' (Sunan an-Nasa''i 3220).','introduction',2,'["verbal","visual"]','["fq-045"]','marriage contract example, wali discussion'),
    ('fq-054','fiqh','fiqh-business',6,'6-7','Business Ethics in Islam — Honest Trade','Be honest in trade: no cheating, no lying about products, fulfill promises. No riba (interest). Refer to Quran 2:275, hadith: ''The honest, trustworthy merchant is with the prophets.'' (Sunan al-Tirmidhi 1209).','practice',2,'["verbal","hands-on"]','["fq-045"]','trade role play, ethics scenarios'),
    ('fq-055','fiqh','fiqh-purity',6,'6-7','Istinja and Istijmar — Cleaning After Using Toilet','Use water (istinja) or stones (istijmar) to clean after using the toilet. Use left hand. Say the dua after: ''Ghufranak.'' Refer to Sahih al-Bukhari 151, Sahih Muslim 271.','practice',2,'["verbal"]','["fq-033"]','toilet etiquette poster, dua card'),
    ('fq-056','fiqh','fiqh-salah',6,'6-7','Praying at the Right Time — Fard vs Missed Prayers','Pray each salah on time. If missed, pray it as soon as possible (qada). Do not deliberately delay. Refer to Quran 4:103: ''Indeed, prayer has been decreed upon the believers at fixed times.''','practice',2,'["verbal"]','["fq-045"]','prayer time chart, qada tracker'),
    ('fq-057','fiqh','fiqh-salah',6,'6-7','Friday Prayers — Jumu''ah','Friday prayer is obligatory for men. It includes a khutbah (sermon) and two rak''ahs. Bathe, wear best clothes, come early. Refer to Quran 62:9-11.','practice',2,'["verbal","visual"]','["fq-045"]','Jumuah preparation checklist, khutbah discussion'),
    ('fq-058','fiqh','fiqh-adab',6,'6-7','Islamic Manners — Comprehensive Adab','Adab in eating (basmalah, right hand, share food), sleeping (sunnah dua, right side), entering/leaving home (dua), entering/leaving mosque. Refer to Sahih al-Bukhari 6313, 6324.','mastery',3,'["verbal","hands-on"]','["fq-020"]','adab booklet project, daily adab tracker');`);

  // =========================================================================
  // SEERAH — Levels 0-6
  // =========================================================================

  console.log("  Batch 3: seerah levels 0-1");
  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
    ('se-001','seerah','seerah-early-life',0,'0-1','Prophet Muhammad ﷺ Loves Children','The Prophet ﷺ was very gentle and loving with children. He would kiss them, play with them, and carry them. Refer to Sahih al-Bukhari 6038.','introduction',2,'["visual","verbal"]','[""]','picture book, gentle storytelling'),
    ('se-002','seerah','seerah-character',0,'0-1','Saying Bismillah — The Prophet''s Way','The Prophet ﷺ taught us to say Bismillah before everything we do. He always began with Allah''s name. Refer to Sunan an-Nasa''i 5525.','introduction',2,'["verbal"]','[""]','mealtime routine, parent modeling'),
    ('se-003','seerah','seerah-early-life',0,'0-1','The Prophet ﷺ Was Kind and Gentle','Simple stories showing the Prophet''s ﷺ kindness — helping others, smiling, speaking softly. Refer to hadith: ''The best of you is the best in character.'' (Sahih al-Bukhari 6037).','introduction',2,'["visual","verbal"]','[""]','simple storybook, toy figures');`);
  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
    ('se-004','seerah','seerah-character',1,'1-2','The Prophet ﷺ Was Kind to Everyone','He was kind to children, elders, rich, poor, Muslims, and non-Muslims. Refer to Quran 21:107: ''We have not sent you except as a mercy to all the worlds.''','introduction',2,'["verbal","visual"]','["se-003"]','story cards, kindness activity'),
    ('se-005','seerah','seerah-character',1,'1-2','The Prophet ﷺ Had a Cat Named Muezza','The Prophet ﷺ loved animals. His cat Muezza would sleep on his robe, and he would cut the sleeve rather than wake her. Refer to various seerah sources.','introduction',2,'["verbal","visual"]','["se-003"]','cat picture, animal kindness discussion'),
    ('se-006','seerah','seerah-character',1,'1-2','The Prophet ﷺ Played with Children','The Prophet ﷺ would race with Aisha (RA) and laugh with children. He taught us that playing is not wrong. Refer to Sahih Muslim 891.','introduction',2,'["verbal","hands-on"]','["se-003"]','racing game, playful activities'),
    ('se-007','seerah','seerah-early-life',1,'1-2','Prophet Ibrahim (AS) and His Family','Simple story: Ibrahim (AS) loved Allah, left his people, and took his wife Hajar and son Ismail to Makkah. Refer to Quran 21:69-83.','introduction',2,'["verbal","visual"]','["se-003"]','simple picture cards, storytelling');`);
  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
    ('se-008','seerah','seerah-early-life',2,'2-3','Prophet Ibrahim (AS) Built the Ka''bah','Ibrahim and his son Ismail built the Ka''bah as the first house of worship for Allah. Refer to Quran 2:127: ''And [mention] when Abraham was raising the foundations of the House...''','introduction',2,'["verbal","visual"]','["se-007"]','Ka''bah model craft, building blocks'),
    ('se-009','seerah','seerah-early-life',2,'2-3','Hajar in the Desert — Zamzam','When Ibrahim left Hajar and baby Ismail in the desert, Hajar ran between Safa and Marwa looking for help. Allah sent the Zamzam spring. Refer to Sahih al-Bukhari 336.','introduction',2,'["verbal","visual"]','["se-007"]','water table activity, storytelling'),
    ('se-010','seerah','seerah-character',2,'2-3','The Prophet ﷺ Was Honest — Al-Amin','Before and after prophethood, the Prophet ﷺ was known as Al-Amin (the trustworthy). The people of Makkah trusted him with their valuables. Refer to seerah sources.','practice',2,'["verbal","visual"]','["se-004"]','honesty role play, trust activity'),
    ('se-011','seerah','seerah-character',2,'2-3','The Prophet ﷺ Loved His Neighbors','The Prophet ﷺ said: ''Jibril kept telling me about the rights of neighbors until I thought he would make them heirs.'' (Sahih al-Bukhari 6014).','practice',2,'["verbal"]','["se-004"]','neighbor kindness cards, drawing activity'),
    ('se-012','seerah','seerah-prophets',2,'2-3','Prophet Yusuf (AS) — A Story of Patience','Yusuf (AS) was thrown in a well by his brothers, but Allah raised him to be a leader in Egypt. Patience and trust in Allah bring relief. Refer to Quran 12:1-101.','introduction',2,'["verbal","visual"]','["se-007"]','story sequencing cards, coloring'),
    ('se-013','seerah','seerah-prophets',2,'2-3','Prophet Musa (AS) and the Bullfrog','Simple retelling of how baby Musa was placed in the river and found by Fir''awn''s family. Allah protected him. Refer to Quran 28:7-13.','introduction',2,'["verbal","visual"]','["se-007"]','water play, baby Moses craft'),
    ('se-014','seerah','seerah-early-life',2,'2-3','Prophet Muhammad ﷺ is the Last Prophet','Muhammad ﷺ was sent to all people, in all places, until the Day of Judgment. Refer to Quran 33:40: ''Muhammad is not the father of any of your men, but the Messenger of Allah and the Seal of the Prophets.''','introduction',2,'["verbal","visual"]','["se-010"]','prophet timeline, nasheed');`);
  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
    ('se-015','seerah','seerah-early-life',3,'3-4','Birth of Prophet Muhammad ﷺ — Year of the Elephant','Muhammad ﷺ was born in Makkah on a Monday in the Year of the Elephant (570 CE). Refer to Quran 105:1-5 (Surah Al-Fil).','introduction',2,'["verbal","visual"]','["se-014"]','seerah timeline, elephant story cards'),
    ('se-016','seerah','seerah-early-life',3,'3-4','Halimah the Wet Nurse — Childhood in the Desert','Muhammad ﷺ was sent to a Bedouin woman named Halimah. He grew up in the pure desert air. Refer to seerah sources by Ibn Kathir.','introduction',2,'["verbal","visual"]','["se-015"]','desert scene pictures, storytelling'),
    ('se-017','seerah','seerah-early-life',3,'3-4','The Splitting of His Chest — Miracle Before Prophethood','An angel opened the young Muhammad''s ﷺ chest, washed his heart with Zamzam, and filled it with faith and wisdom. Refer to Sahih al-Bukhari 3343.','introduction',2,'["verbal"]','["se-015"]','simple illustration, respectful discussion'),
    ('se-018','seerah','seerah-makkah',3,'3-4','First Revelation in Cave Hira — Iqra','Jibril came to Muhammad ﷺ in Cave Hira and said ''Read!'' three times. This was the first revelation: Surah Al-''Alaq 96:1-5. Refer to Sahih al-Bukhari 3.','introduction',3,'["verbal","visual"]','["se-015"]','cave craft (dark room with light), Iqra poster'),
    ('se-019','seerah','seerah-makkah',3,'3-4','Khadijah (RA) — The First Believer','Khadijah bint Khuwaylid was the first person to believe in Muhammad ﷺ. She was his wife, supporter, and comfort. Refer to seerah sources.','introduction',2,'["verbal","visual"]','["se-018"]','story card, Khadijah tribute drawing'),
    ('se-020','seerah','seerah-makkah',3,'3-4','Waraqah ibn Nawfal — Recognized the Revelation','Waraqah was a Christian scholar who recognized that Jibril had come to Muhammad ﷺ with the same revelation that came to Musa. Refer to Sahih al-Bukhari 3.','introduction',2,'["verbal"]','["se-018"]','story cards, timeline'),
    ('se-021','seerah','seerah-character',3,'3-4','The Prophet ﷺ Was the Best in Character','Refer to Quran 68:4: ''And indeed, you are of a great moral character.'' He was patient, generous, truthful, merciful, and humble.','practice',2,'["verbal","visual"]','["se-004"]','character trait poster, self-reflection'),
    ('se-022','seerah','seerah-prophets',3,'3-4','Prophet Nuh (AS) — The Patient Caller','Nuh (AS) called his people to Allah for 950 years. He endured mockery and rejection. Allah saved him in the ark. Refer to Quran 11:25-49.','practice',2,'["verbal","visual"]','["se-012"]','ark craft, flood story sequencing');`);
  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
    ('se-023','seerah','seerah-makkah',4,'4-5','Secret Da''wah in Makkah — First Three Years','For the first three years, Islam was preached in secret. The early believers met secretly in the house of Al-Arqam. Refer to seerah sources by Ibn Kathir.','introduction',2,'["verbal","visual"]','["se-018"]','secret meeting role play, timeline'),
    ('se-024','seerah','seerah-makkah',4,'4-5','Persecution of Early Muslims','The Quraysh tortured Muslims: Bilal was dragged with rocks, Sumayyah was martyred, Ammar was tortured. They remained patient. Refer to seerah sources.','introduction',3,'["verbal","visual"]','["se-023"]','story cards, patience discussion'),
    ('se-025','seerah','seerah-makkah',4,'4-5','First Migration to Abyssinia — Seeking Refuge','Some Muslims migrated to Abyssinia (Ethiopia), where the just King Ashamah (Najashi) protected them. Refer to Sahih al-Bukhari 4361.','practice',2,'["verbal","visual"]','["se-024"]','map activity, Ashamah story'),
    ('se-026','seerah','seerah-makkah',4,'4-5','Boycott of Banu Hashim — Three Years of Hardship','The Quraysh boycotted the Prophet''s ﷺ family for three years. They ate leaves and leather to survive. Refer to seerah sources.','practice',2,'["verbal","visual"]','["se-024"]','hardship vs patience discussion, timeline'),
    ('se-027','seerah','seerah-makkah',4,'4-5','Year of Sorrow — Losing Khadijah and Abu Talib','In the same year, the Prophet ﷺ lost his beloved wife Khadijah (RA) and his uncle Abu Talib, who protected him. This was the hardest year. Refer to seerah sources.','practice',2,'["verbal"]','["se-023"]','respectful storytelling, emotional discussion'),
    ('se-028','seerah','seerah-madinah',4,'4-5','Migration to Madinah (Hijrah) — The Journey','The Prophet ﷺ migrated from Makkah to Madinah with Abu Bakr (RA). They hid in Cave Thawr for three days. Refer to Quran 9:40.','introduction',3,'["verbal","visual"]','["se-027"]','map, cave craft, journey storytelling'),
    ('se-029','seerah','seerah-madinah',4,'4-5','Arrival in Madinah — The Ansar Welcomed Them','The people of Madinah (the Ansar) joyfully welcomed the Prophet ﷺ and the Muhajireen. They sang: ''Tala''al Badru Alayna.'' Refer to seerah sources.','introduction',2,'["verbal","hands-on"]','["se-028"]','nasheed (Tala''al Badru), welcome cards'),
    ('se-030','seerah','seerah-madinah',4,'4-5','Brotherhood (Mu''akhat) — Muhajireen and Ansar','The Prophet ﷺ paired each Muhajir with an Ansari as brothers. They shared homes, wealth, and everything. Refer to Sahih al-Bukhari 3788.','practice',2,'["verbal","hands-on"]','["se-028"]','brotherhood pairs activity, sharing game'),
    ('se-031','seerah','seerah-madinah',4,'4-5','Building Masjid an-Nabawi — The Prophet''s Mosque','The Prophet ﷺ personally helped build the first mosque in Madinah. He laid the foundation with his own hands. Refer to Sahih al-Bukhari 442.','practice',2,'["hands-on","verbal"]','["se-028"]','mosque model craft, building activity'),
    ('se-032','seerah','seerah-prophets',4,'4-5','Prophet Ibrahim (AS) — Destroying the Idols','When Ibrahim (AS) saw his people worshipping idols, he smashed them all, leaving the largest. He said: ''Do you worship what you yourselves have carved?'' Refer to Quran 21:51-67.','practice',2,'["verbal","visual"]','["se-012"]','idol smashing activity (clay), discussion');`);
  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
    ('se-033','seerah','seerah-battles',5,'5-6','Battle of Badr — 313 vs 1000','The first major battle. 313 poorly equipped Muslims faced 1000 well-armed Quraysh. Allah sent angels to help. 70 enemies were killed, 70 captured. Refer to Quran 3:123-125, Sahih al-Bukhari 395.','practice',3,'["verbal","visual"]','["se-031"]','battle map, numbers comparison, trust discussion'),
    ('se-034','seerah','seerah-battles',5,'5-6','Battle of Uhud — Lessons from Setbacks','The Muslims initially gained the upper hand, but some archers disobeyed orders. Hamza (RA) was martyred. The Prophet ﷺ was injured but forgave the people of Makkah. Refer to Quran 3:139-152.','practice',2,'["verbal","visual"]','["se-033"]','lessons learned chart, resilience discussion'),
    ('se-035','seerah','seerah-battles',5,'5-6','Battle of the Trench (Khandaq) — Strategy and Trust','The Muslims dug a trench around Madinah to defend against 10,000 enemies. Salman Al-Farisi (RA) suggested the strategy. Refer to Quran 33:9-27.','practice',2,'["verbal","hands-on"]','["se-033"]','trench digging (sandbox), strategy discussion'),
    ('se-036','seerah','seerah-madinah',5,'5-6','Treaty of Hudaybiyyah — Peace and Wisdom','The Muslims wanted to perform Umrah but were stopped at Hudaybiyyah. The treaty seemed unfavorable, but Allah called it a ''clear victory.'' Refer to Quran 48:1.','practice',2,'["verbal","visual"]','["se-033"]','treaty negotiation role play, wisdom discussion'),
    ('se-037','seerah','seerah-madinah',5,'5-6','Conquest of Makkah — Forgiveness and Mercy','In 8 AH, the Prophet ﷺ entered Makkah with 10,000 Muslims. He forgave his enemies and said: ''Go, you are all free.'' Refer to seerah sources, Sahih al-Bukhari 3970.','practice',2,'["verbal","visual"]','["se-036"]','forgiveness story, conquest timeline'),
    ('se-038','seerah','seerah-battles',5,'5-6','Battle of Hunayn and the Conquest of Ta''if','After Makkah, the Muslims faced tribal resistance. The Prophet ﷺ showed mercy and sent a delegation to the people of Ta''if inviting them to Islam.','practice',2,'["verbal","visual"]','["se-037"]','mercy map, delegation story'),
    ('se-039','seerah','seerah-character',5,'5-6','Character of Prophet ﷺ — Comprehensive Study','The Prophet ﷺ was: patient, generous, truthful, humble, merciful, just, brave, and playful. His wife Aisha (RA) described his character as ''the Quran walking among people.'' (Sahih Muslim 746).','mastery',4,'["verbal","visual","hands-on"]','["se-037"]','character booklet project, hadith collection'),
    ('se-040','seerah','seerah-companions',5,'5-6','Abu Bakr As-Siddiq (RA) — The Truthful','First man to accept Islam. He spent all his wealth to free Muslim slaves. He became the first Caliph. Refer to Quran 9:40.','practice',2,'["verbal","visual"]','["se-037"]','companion profile card, biography reading'),
    ('se-041','seerah','seerah-companions',5,'5-6','Umar ibn Al-Khattab (RA) — The Just','Second Caliph. Known for his strict justice. Established the Islamic state apparatus. Refer to hadith in Sahih al-Bukhari 1393.','practice',2,'["verbal","visual"]','["se-040"]','companion profile card, justice discussion'),
    ('se-042','seerah','seerah-companions',5,'5-6','Uthman ibn Affan (RA) — The Generous','Third Caliph. Bought the well of Rumah for public use. Funded the Muslim army. Bought copies of the Quran for all provinces. Refer to seerah sources.','practice',2,'["verbal","visual"]','["se-040"]','generosity activity, companion card'),
    ('se-043','seerah','seerah-companions',5,'5-6','The Prophet''s ﷺ Family — Khadijah, Fatimah, Hasan and Husayn','Brief overview of the Prophet''s ﷺ household: Khadijah (first wife), Fatimah (beloved daughter), Hasan and Husayn (beloved grandsons).','practice',2,'["verbal","visual"]','["se-039"]','family tree, family cards'),
    ('se-044','seerah','seerah-madinah',5,'5-6','Life in Madinah — Building the Ummah','The Prophet ﷺ established a just society: the Constitution of Madinah, market of Anas, equal rights for all citizens. Refer to seerah sources.','practice',2,'["verbal","visual"]','["se-031"]','constitution discussion, society building');`);
  await prisma.$executeRawUnsafe(`INSERT INTO "CurriculumTopic" (id,subject,strand,level,"ageGroup",title,description,category,"estimatedSessions",tags,prerequisites,materials) VALUES
    ('se-045','seerah','seerah-madinah',6,'6-7','Complete Seerah Timeline — Birth to Death','Comprehensive timeline: birth (570 CE), first revelation (610 CE), hijrah to Madinah (622 CE), battles, conquest of Makkah (630 CE), farewell hajj (632 CE), death (632 CE).','practice',4,'["visual","verbal"]','["se-039"]','full timeline poster, project booklet'),
    ('se-046','seerah','seerah-madinah',6,'6-7','Letters to Kings and Rulers','The Prophet ﷺ sent letters inviting kings to Islam: Heraclius (Byzantine), Chosroes (Persia), Muqawqis (Egypt), Negus (Abyssinia), and others. Refer to Sahih al-Bukhari 7, 15.','practice',2,'["verbal","visual"]','["se-045"]','world map, letter cards, ruler profiles'),
    ('se-047','seerah','seerah-madinah',6,'6-7','Farewell Hajj and the Farewell Sermon','In 10 AH, the Prophet ﷺ performed his only Hajj and delivered a powerful sermon: ''All mankind is from Adam... your blood, property, and honor are sacred.'' Refer to Sahih al-Bukhari 1623, Sahih Muslim 1218.','practice',2,'["verbal","visual"]','["se-045"]','sermon key points poster, Hajj journey map'),
    ('se-048','seerah','seerah-madinah',6,'6-7','Death of the Prophet ﷺ — The Ummah''s Grief','The Prophet ﷺ passed away on a Monday in Rabi'' al-Awwal 11 AH. Umar (RA) could not accept it. Abu Bakr (RA) reminded: ''Whoever worshipped Muhammad, know that Muhammad has died. Whoever worshipped Allah, know that Allah is alive and never dies.'' Refer to Sahih al-Bukhari 1234.','practice',2,'["verbal"]','["se-047"]','respectful discussion, legacy reflection'),
    ('se-049','seerah','seerah-madinah',6,'6-7','His Legacy — What the Prophet ﷺ Left for Us','The Prophet ﷺ left us: the Quran, the Sunnah, his example, and the Ummah. His legacy continues through every Muslim who follows his way. Refer to Quran 3:31: ''Follow me; Allah will love you.''','mastery',3,'["verbal","visual"]','["se-048"]','legacy project, personal reflection essay'),
    ('se-050','seerah','seerah-companions',6,'6-7','Ali ibn Abi Talib (RA) — The Lion of Allah','Fourth Caliph. First male to accept Islam. Known for knowledge, courage, and justice. Refer to seerah sources and hadith about his virtues.','practice',2,'["verbal","visual"]','["se-041"]','companion profile, knowledge discussion'),
    ('se-051','seerah','seerah-companions',6,'6-7','Khalid ibn Al-Walid (RA) — Sword of Allah','Greatest Muslim general. Won many battles for Islam. Was known as Sayfullah (Sword of Allah). Refer to seerah sources.','practice',2,'["verbal","visual"]','["se-041"]','companion profile, military strategy discussion'),
    ('se-052','seerah','seerah-companions',6,'6-7','Bilal ibn Rabah (RA) — The First Muezzin','A freed slave who became the first muezzin. He was tortured for his faith but never gave up. His beautiful voice would call people to prayer. Refer to Sahih al-Bukhari 3823.','practice',2,'["verbal","visual"]','["se-041"]','adhan practice, perseverance story'),
    ('se-053','seerah','seerah-companions',6,'6-7','Salman Al-Farisi (RA) — The Persian Companion','Salman traveled from Persia searching for truth. He became Muslim and suggested digging the trench at the Battle of the Khandaq. Refer to seerah sources.','practice',2,'["verbal","visual"]','["se-050"]','journey map, truth-seeking discussion'),
    ('se-054','seerah','seerah-companions',6,'6-7','Hamza ibn Abdul Muttalib (RA) — Lion of Allah','The Prophet''s ﷺ uncle and brave warrior. Martyred at Uhud. His acceptance of Islam strengthened the early Muslims. Refer to seerah sources.','practice',2,'["verbal","visual"]','["se-034"]','companion profile, bravery discussion'),
    ('se-055','seerah','seerah-character',6,'6-7','The Prophet''s ﷺ Daily Routine','From seerah sources: He would wake for Fajr, pray sunnah prayers, read Quran until sunrise, go to the market, return, pray Dhuhr, rest, pray Asr, spend time with family, pray Maghrib, and pray Isha. Refer to Sahih al-Bukhari 5067, Sahih Muslim 731.','practice',2,'["verbal","visual"]','["se-039"]','daily routine chart, routine comparison'),
    ('se-056','seerah','seerah-madinah',6,'6-7','Seerah and Quran Connection — Verses Revealed About Events','Many Quran verses were revealed about specific events: Battle of Badr (3:123), Treaty of Hudaybiyyah (48:1), Ifk incident (24:11-20). Understanding context deepens Quran study.','practice',3,'["verbal","visual"]','["se-045"]','Quran-seerah matching cards, context study'),
    ('se-057','seerah','seerah-madinah',6,'6-7','Importance of Following the Sunnah — The Way of the Prophet ﷺ','The Sunnah explains and clarifies the Quran. Following the Sunnah is obligatory. Refer to Quran 3:31: ''Say: If you love Allah, then follow me; Allah will love you.'' Refer to hadith about clinging to the Sunnah in Sahih al-Bukhari 2455.','practice',2,'["verbal"]','["se-049"]','Sunnah vs culture discussion, practical application'),
    ('se-058','seerah','seerah-character',6,'6-7','Lessons from Seerah for Our Daily Lives','Applying seerah lessons: patience in hardship (Hijrah), forgiveness (Conquest of Makkah), justice (Umar RA), generosity (Uthman RA), courage (Ali RA), trust in Allah (Badr).','mastery',3,'["verbal","hands-on"]','["se-045","se-049"]','personal seerah application journal, group project');`);

  const aqCount = 58;
  const fqCount = 58;
  const seCount = 58;
  const total = aqCount + fqCount + seCount;
  console.log(`Seeded ${total} Islamic curriculum topics:`);
  console.log(`  Aqeedah: ${aqCount} topics (aq-001 to aq-058)`);
  console.log(`  Fiqh: ${fqCount} topics (fq-001 to fq-058)`);
  console.log(`  Seerah: ${seCount} topics (se-001 to se-058)`);
  console.log("Islamic curriculum seeding complete!");
}
